### ISSUE TITLE
HaaS should have a method of wiping disks

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#105]
Sharing hardware between tenants means that we should try to reset the state of each node each time it becomes free, so that the next time it is allocated there is no state carried over.

 To do this, we should wipe disks. This could be done by PXE booting into a small, in-memory OS and running some logic.

Bonus points for using SATA's secure erase.

The [Ironic python agent](https://wiki.openstack.org/wiki/Ironic-python-agent) may solve some/all of this.

**Comment by Izhmash** [comment]
The maintenance service will now do this. #891
