### ISSUE TITLE
More descriptive error messages/status codes for APIErrors

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#191]
It would be nice if the haas server returned more intelligible errors to the client. This should be achievable in a reasonably elegant way by adding appropriate functionality to the subclasses of `APIError`.

**Comment by xuhang57** [comment]
@zenhack maybe we can close this for now?

**Comment by naved001** [comment]
The issue isn't entirely solved. There's more discussion on the related issue #925 so I'll close this one in favor of that. Please reopen if you think this warrants a separate discussion.
