### ISSUE TITLE
Server should exit with an intelligible error message if the database is not initialized properly upon startup.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#232]
Right now you just get an `IntegretyError` the first time someone makes an API call. This can happen not only if the database hasn't been created/initialized, but also if the developer has changed the schema.

**Comment by matsuuran** [comment]
@zenhack are you seeing this in a prod version or in the dev versions as well

**Comment by zenhack** [comment]
Not sure exactly what you mean by prod vs. dev. First, it's worth noting that this bug was opened a *really* long time ago. I just checked, and it now does throw an error on startup, because `stop_orphan_consoles()` tries to execute a query. the report is still a big stack trace though, and we shouldn't be relying on that sort of thing to pick up errors.

I've tried this via `haas serve` with both postgres and sqlite, but not behind a real web server like apache, though I would expect the same behavior (if not, something is amiss).

The exact exception that gets thrown is dependent on the backend; postgres throws a `psycopg2.ProgrammingError`, while sqlite throws a `sqlalchemy.exc.OperationalError`.

**Comment by zenhack** [comment]
Alembic stores version information in a dedicated table in the database, so we can just query that table to see if we're up to date, and exit with an intelligible error if not. Probably using this from the alembic library:

http://alembic.zzzcomputing.com/en/latest/api/script.html#alembic.script.ScriptDirectory.get_heads

**Comment by zenhack** [comment]
I'm going to self-assign, I'll get to this soonish.

**Comment by henn** [comment]
@zenhack - do you think you'll still have time for this? We'd like to finish it up in the next 3 or 4 weeks or so. Thx

**Comment by zenhack** [comment]
Yeah, I can definitely get it in in that time frame. Sorry for the delay.
