### ISSUE TITLE
Mechanism for updating database schema

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#233]
Once this is in deployment, we'll have less freedom wrt changing the database schema -- for any changes we make, we'll need to have a way to update the databases of existing installations, since simply deleting the database and starting fresh (which is what we've been doing in development) won't be an acceptable solution

**Comment by naved001** [comment]
we have migration scripts for that now, yeah? can we close this?

**Comment by zenhack** [comment]
Yep, closing.
