### ISSUE TITLE
Interface to set a node's next boot device

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#303]
We should have an interface that allows a user to set the next boot device, likely either PXE or local disk. API should leave open the possibility of other boot sources (like a virtual disk drive).

Perhaps we could even allow them to set it persistently, assuming IPMI supports that? If that happened, we should likely reset that on node delete,

**Comment by zenhack** [comment]
What's our current thinking on this? Now that HIL has seen a bit more use, has anyone found themselves actually wanting this? Per my comments back when this was opened, we can't actually change the boot order for more than the next boot, and calling shutdown from within the OS wil bypass our setting here anyway.

**Comment by zenhack** [comment]
@henn, thoughts?

**Comment by naved001** [comment]
It seems like IPMI supports setting the boot device persistently. 

> [naved001@haas-beta ~]$ ipmitool -I lanplus -U $USER -P $PASSWORD -H $HOSTNAME chassis bootdev disk options=help
Legal options settings are:
	help:	print this message
	valid:	Boot flags valid
	**persistent: Changes are persistent for all future boots**
	efiboot:	Extensible Firmware Interface Boot (EFI)
	clear-cmos:	CMOS clear
	lockkbd:	Lock Keyboard
	screenblank:	Screen Blank
	lockoutreset:	Lock out Resetbuttons
	lockout_power:	Lock out (power off/sleep request) via Power Button
	verbose=default:	Request quiet BIOS display
	verbose=no:	Request quiet BIOS display
	verbose=yes:	Request verbose BIOS display
	force_pet:	Force progress event traps
	upw_bypass:	User password bypass
	lockout_sleep:	Log Out Sleep Button
	cons_redirect=default:	Console redirection occurs per BIOS configuration setting
	cons_redirect=skip:	Suppress (skip) console redirection if enabled
	cons_redirect=enable:	Suppress (skip) console redirection if enabled

I should test this to make sure it works as expected.

**Comment by zenhack** [comment]
I vaguely remember testing that and finding that it didn't work, but that may have been with the old sun blades, in which case it might make sense to try it with newer gear.

**Comment by henn** [comment]
#699 fixes this!
