### ISSUE TITLE
WIP Passwords present in logs

### ISSUE THREAD

**Issue by gsilvis** [CCI-MOC/hil#306]
`moc.rest` is logging all API calls, with all parameters---and the `user_create` API call contains a password as a parameter.  So, `moc.rest` logs the password, too.

**Comment by zenhack** [comment]
Spitballing: What if we added a decorator that let's us tag arguments as "don't log"? e.g.:

```python
@rest_call(...)
@dont_log('password')
def user_create(user, password, is_admin=False):
   ...
```

I think we can implement this by doing something like `setattr(f, 'dont_log_args', ...)` in the decorator, and then check for that attribute before we do the logging.

Thoughts?

**Comment by zenhack** [comment]
@gsilvis, @henn, can you weigh inon my proposal?

**Comment by gsilvis** [comment]
Perhaps make it an optional parameter to rest_call?  Seems a little less hacky to implement it that way.

**Comment by zenhack** [comment]
Sounds good; then we can just pass it in to `_rest_wrapper` and use it there.

**Comment by zenhack** [comment]
@henn, thoughts?

**Comment by shwsun** [comment]
@henn I think what @zenhack proposed seemed to be a good solution, any thoughts on this?

**Comment by henn** [comment]
Passing it as a parameter into `@rest_call` sounds good to me!

**Comment by zenhack** [comment]
@shwsun, this is assigned to you, and it looks like we have an agreed-upon solution. Do you want to tackle this? If not I can just grab it; I've got the time to pick through issues and there's nothing on the 0.2 milestone that doesn't have an assignee.

**Comment by shwsun** [comment]
Hi @zenhack , it would be good if you want to take it since there are probably more I have to dig while I am a bit busy this semester. I will be doing code review if you have a PR pushed.

**Comment by zenhack** [comment]
Cool, I've assigned myself.

**Comment by henn** [comment]
Hey @zenhack - do you think you'll have time to work on this in the next 2 weeks?

Thanks

**Comment by zenhack** [comment]
@henn, yep; I've some WIP kicking around on my hard drive already.
