### ISSUE TITLE
More consistent terminology

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#312]
There are a number of concepts in the HaaS that we have redundant names for throughout the code, which makes variable names less consistent and thus less predictable. Here are some examples:
- [ ] name/label

...okay just the one example for now. We can edit this if/when we find more, I feel like they're there.

**Comment by xuhang57** [comment]
@zenhack  
What I think of is that having a new docs or somewhere in the existing doc, list the common definition about HIL terminology such as 

name/label
Client Library: Python Client Library (hil/client/)
CLI: Command Line Tools (hil/cli.py)
API: REST API (hil/api.py)
project
network
node
switch
...

any thoughts? 

@naved001

**Comment by naved001** [comment]
I don't know if documenting it will help. I would rather change it in the code itself (unless it requires changing database columns where I'd rather not add a migration script just for changing names).

**Comment by xuhang57** [comment]
True, so there is no actionable tasks we can think of at the moment. We should close this issue if @zenhack has no issue with it.

**Comment by xuhang57** [comment]
@zenhack closing this now. feel free to reopen it.
