### ISSUE TITLE
record successful application of networks one at a time.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#314]
Right now `serve_networks()` clears pending actions in one transaction, at the very end of its operation. This is suboptimal, since it means a failure in the middle will cause _all_ actions to be reapplied, even ones which are complete.

The code should be reorganized a bit to facilitate this; in particular, doing them all at once allows us to avoid logging into the switch multiple times. Getting the best of both works would require a bit of refactoring.

**Comment by henn** [comment]
I think this is actually a pretty simple change, and would increase the robustness of HaaS by not allowing one error in any operation to cause all operations to fail. Operations in the same queue as the failing one will also reflect incorrectly in the DB (and thus the future ``show_network()``). Optimization (like having multiple service threads or connection pooling) should be treated as a separate issue.

It could be done within deferred.py's ``apply_networking()`` by placing the bulk of the body inside of a while loop that is keyed off of:
```python
action = db.query(model.NetworkingAction).\
             order_by(model.NetworkingAction.id).first()
```

See SQLAlchemy's [first()](http://docs.sqlalchemy.org/en/rel_0_9/orm/query.html#sqlalchemy.orm.query.Query.first) function for info on semantics.

It might make sense to move to some sort of Reliable Message Queue when it's needed @zenhack, however I think for now using a DB table in a sensible way will get us a lot of the way there.

**Comment by zenhack** [comment]
I'd want to actually measure the time it takes to log into and out of the switch before making this change -- It may well be simply too big not to batch the applications.

If this is the case, the solution is easy enough: expose connect/disconnect. On my vlan-trunking branch these are already separated out (just for cleanliness purposes) so it wouldn't be hard to make it a public api. then we can just put the connect/disconnect around your proposed loop.

**Comment by zenhack** [comment]
Observation: the implementation is changed such that connections to the switches are created on first use, so the overhead we were discussing for not batching the actions is no longer there. doing a commit after each action seems sensible. I'd like to pin down where #508 is going, but this seems straightforward in and of itself.

**Comment by matsuuran** [comment]
would it be okay to close the sessions after the db commits, so we'd go from two loops on actions to one?

**Comment by zenhack** [comment]
@matsuuran, that's what I had in mind.

**Comment by naved001** [comment]
@henn this is the only 0.2 bug left now

**Comment by zenhack** [comment]
I'm going to take @matsuuran off of this. Does anyone else want to pick this one up?

**Comment by naved001** [comment]
@zenhack @henn 

```python
@@ -101,7 +101,7 @@ def apply_networking():
     session = DaemonSession()
     for action in actions:
         session.handle_action(action)
+        model.NetworkingAction.query.filter_by(id=action.id).delete()
+        db.session.commit()
     session.close()
-    model.NetworkingAction.query.delete()
-    db.session.commit()
     return True
```

Why can't we just do this?

**Comment by zenhack** [comment]
@naved001, I think that does work -- would want some tests, obviously, which was the bigger part of #673, and I the bit that it got stalled on. The rest of it was a fairly simple change at the time, though it's bitrotten beyond recovery at this point.

If you want to wrap that up in a pr with some tests, we can knock this off the list.

**Comment by zenhack** [comment]
What I'm not sure about is whether it's safe to modify the contents of that query while iterating over it, but if not we can just store stuff in a list first.
