### ISSUE TITLE
Integer may be too small to ensure network action ordering.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#315]
@henn brought this up. We're using the primary key for our network actions to determine ordering, and on most databases `Integer`is a 32-bit signed int. It's possible that a long-running HaaS installation might overflow eventually; my back-of-the-napkin estimates put this at ~3.5 years if you accumulate ten actions per second.

Using a 64 bit number would be more than sufficient to prevent this.

EDITED BY HENN (6/7/2017) to add checklist we discussed:

- [x] Do first PR with one migration.
- [x] Do the rest

**Comment by Izhmash** [comment]
I've been working on finishing this one up.  Currently reviewing my changes and writing some tests.

**Comment by Izhmash** [comment]
Since I'm changing the primary keys in core `haas`, `haas.ext.switches.mock`, and `haas.ext.obm.mock`, do I need to have three separate migrations? Or do I only need one for all three?

**Comment by zenhack** [comment]
You need separate ones -- the ones for extensions should only get run if those extensions are loaded.

**Comment by Izhmash** [comment]
@henn Would you like me to add the overflow test we discussed before I start the pull request?

**Comment by henn** [comment]
Checklist we discussed:

- [ ] Do first PR with one migration.
- [ ] Do the rest

**Comment by SahilTikale** [comment]
Blocked on #805

**Comment by Izhmash** [comment]
Addressed by #839
