### ISSUE TITLE
Option to cause 'haas serve' to also run the 'serve_networks()' function

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#317]
As part of #296 and later a comment in #309, it was brought up that having an option to run serve_networks() as part of the main haas process could be desirable for developing/testing due to a) having all messages going to a single window and b) necessitating less overhead for the development/test modify/run cycle.

This could be done either as a separate process or as a separate thread (via [multiprocess](https://docs.python.org/2/library/multiprocessing.html) or [threading](https://docs.python.org/2/library/threading.html#module-threading)).

**Comment by henn** [comment]
This should be done after the new CLI in #431.

**Comment by naved001** [comment]
I don't feel strongly about this; specially since this is only for development.

I prefer that the commands going to the switch are in a different window and api calls are in another.

@SahilTikale @Izhmash @zenhack @henn you guys wanna vote on this (or discuss the pros and cons)

**Comment by zenhack** [comment]
Eh, I think it's not really worth the complexity. I also think there's some value in developers needing to know about the network daemon, and keeping this manual makes sure people see it (if they actually doing anything in dev that needs it, which I often don't). I don't feel strongly though.

**Comment by naved001** [comment]
Let's give others a couple of days before closing this issue.

**Comment by zenhack** [comment]
Sounds good.

**Comment by naved001** [comment]
Closing. Please re-open if you want to discuss this.
