### ISSUE TITLE
Make sleep time for async loop tunable

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#318]
Per review comments on #296, the sleep() time in serve_networks() should be tunable. This should also be documented.

**Comment by Izhmash** [comment]
How tunable should the sleep time be? My first thought is to pass the time as a parameter in serve_networks() but that might not be the right direction.

**Comment by Izhmash** [comment]
@henn Should the solution from #323 that was merged into the devel branch be implemented in master?  It seems that is the accepted solution to this issue.

**Comment by henn** [comment]
@lzhmash Nice find, though I think it only partially addresses the issue. The solution will need to check for configuration from the config file (see uses of `cfg` elsewhere in the code), then pass it to serve_networks() using the solution you found if the configurable was set.

**Comment by naved001** [comment]
Fixed by #785
