### ISSUE TITLE
Fill out metadata in setup.py

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#321]
We're going to want to package the haas and put it on pypi (and probably make rpms/debs). To that end, we should fill out extra metadata in setup.py - things like author{,_email} (probably something like mass open cloud contributors/moc-technical@googlegroups.com), description, etc, as well as the categories field, which we can use to indicate supported python versions, development stage of the project (alpha...).

This applies to moc-rest as well; really wish github let issues span multiple repos.

**Comment by zenhack** [comment]
I've got some work on this on my branch `pypi`. Useful links for RPMs:

* https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/sec-Yum_Repository.html
* https://fedoraproject.org/wiki/How_to_create_an_RPM_package

We'll want to find a place to actually host an RPM repo for HaaS; I think it'll be easier in the long term to be doing deployments from RPMs than the pip stuff we're doing now.

**Comment by naved001** [comment]
Fixed by https://github.com/CCI-MOC/hil/pull/534
