### ISSUE TITLE
haas.cfg should be loaded from more sensible location(s).

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#337]
Right now, the wsgi script loads it from `/etc/haas.cfg`, and the haas command loads it from `./haas.cfg`. This is terrible.

**Comment by matsuuran** [comment]
@zenhack are you looking for wsgi/haas to check `/etc/haas.cfg` and then to check locally or did you have something else in mind?

**Comment by zenhack** [comment]
exact details are up for debate, but it should (a) be at least somewhat consistent between the two, and (b) be fairly idiomatic for unix daemons.

Loading from the current directory is nice from a development standpoint, but we really shouldn't be assuming anything about where apache executes the wsgi script from.

One common (but not universal) way of finding config files is to search for them in priority order, with something like this as the ordering:

1. File specified on the command line, via a `--config` option or the like. we don't do this now partially because the way our cli is set up would require a bit of refactoring, but we want to do that anyway.
2. relative to the current directory, e.g. `./haas.cfg`
3. relative to the users home directory, e.g. `$HOME/.haas.cfg`
4. an absolute path, e.g. `/etc/haas.cfg`

Step (3) doesn't make much sense for the server, but might be nice from the client's perspective. Step (2) makes no sense when run behind apache, and step (1) isn't even possible in that case.

**Comment by shwsun** [comment]
IMO, ``~/.haas.cfg`` would not be necessary. config file should be either in ``/etc/haas.cfg`` or ``./haas.cfg``. More choice would only make it harder to debug if wrong ``haas.cfg`` is loaded.

**Comment by zenhack** [comment]
I don't feel strongly about `~/.haas.cfg`. @shwsun has a point. I'll go along with whatever others think is best.

**Comment by matsuuran** [comment]
for now I'll leave it out and if we decide later that it is nice to have it is easy to add in

**Comment by matsuuran** [comment]
@zenhack if this is the case, because my PR doesn't implement the option to pass in as a command line argument, should we even change this?  Initially I was going to wait for the larger CLI refactoring to add the `--config` option but I could do it now if you see no issue.

**Comment by zenhack** [comment]
Quoting Nicholas Matsuura (2016-08-02 13:24:05)

>    [1]@zenhack if this is the case, because my PR doesn't implement the
>    option to pass in as a command line argument, should we even change
>    this? Initially I was going to wait for the larger CLI refactoring to
>    add the --config option but I could do it now if you see no issue.

The reason it needs to wait for the refactoring is that the way the
module is written we don't have a way of passing flags; all arguments
are strictly positional. The refactoring would use a proper command line
parser library, like argparse or maybe click. I don't think it's worth
writing special purpose code in the meantime.

I don't feel super strongly about what we do with this now. If we leave
it as is I'd like to put a reference in the description for the
refactoring issue so we remember to deal with it when we finally get to
that.

**Comment by matsuuran** [comment]
That's what I thought but I wanted to make sure.

The only difference between what is implemented in #632 is that it will look for `/etc/haas.cfg` by default instead of passing it in.  The way it sounds though the only time we're using that is in the wsgi script, so I don't see a reason to bring it in.

**Comment by zenhack** [comment]
The network daemon also uses it.

**Comment by matsuuran** [comment]
Same use case though where it passes in the location of the config file?  I'm just saying what do we gain from the change

**Comment by henn** [comment]
Note that for clients, `HAAS_ENDPOINT` is used. For clients, we probably shouldn't even try to use haas.cfg.

**Comment by zenhack** [comment]
I think we're fuzzy enough on what this should even be that having an issue open for it isn't really helpful. I propose that we just close this. @henn, @matsuuran, @shwsun, any objections?

**Comment by matsuuran** [comment]
@zenhack I agree, but when the new CLI comes along I think we can still throw in something to load a config file like `--config`

**Comment by zenhack** [comment]
Ok, I put a comment to that effect in #431 so we remember. I'm going to close this. @henn, @shwsun, if you have any objections feel free to repoen.
