### ISSUE TITLE
Make sure the haas does a "force off" with ipmi.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#372]
When doing integration tests for the HaaS release, @lokI8 and I noticed that the sun blades were shutting down _properly_ when we invoked the power cycle api, if they were booted into CentOS. We should make sure it isn't possible for a malicious user to simply "ignore" the shtudown request, thereby hijacking a node that they are supposed to have released.

**Comment by zenhack** [comment]
Apparently the hard reset command is `chassis power reset` whereas we're calling `chassis power cycle`.

**Comment by naved001** [comment]
A duplicate issue is raised here #631. I'll close this issue because the other one has more discussion on it.
