### ISSUE TITLE
"haas init_db" should run as haas_user if run as root

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#387]
If running `haas init_db` as root, the database is created as root and the haas_user cannot access it properly.

init_db should detect if running as root, and if so either su to the haas user (`os.setuid()`) or chown the file as appropriate.

**Comment by zenhack** [comment]
Several problem with this solution:

1. haas_user is an artifact of INSTALL.rst, and thus the haas has no way 
   of knowing, in general, what user to switch to.
2. This requires SQLite specific logic; right now init_db will require 
   no porting work when move to other DBMSes.

I think the right solution is to just get support for a proper database 
server in, and say "don't use SQLite in production.

Quoting henn (2015-01-06 14:51:56)

**Comment by henn** [comment]
Good points.

1) Would there be any other reason to have a "haas_user" config option?

2) running setuid() first could solve the issue in a non-SQLite-specific manner

**Comment by zenhack** [comment]
1) Not really - by the time HaaS reads the config file, in all cases it's running as its final user.

I'm alergic to server software that silently tries to figure out what the user "meant" to do. I'd be okay with having the cli tool spit out a nasty warning/error if run as root.

**Comment by henn** [comment]
You're right. Let's issue a WARNING if uid() == 0 when running ```haas init_db``` so that the user has an idea something might be wrong. Sound good?

When using sqlite, it might also be more user friendly to check permissions on the DB using *os.access()* and print a warning if there is an issue. Currently, the error is a lengthy stack trace ending in something like this:
```
OperationalError: (OperationalError) attempt to write a readonly database u'INSERT INTO node (label, project_id, ipmi_host, ipmi_user, ipmi_pass) VALUES (?, ?, ?, ?, ?)' ...
```

**Comment by zenhack** [comment]
Quoting henn (2015-01-12 22:10:18)
>    You're right. Let's issue a WARNING if uid() == 0 when running haas
>    init_db so that the user has an idea something might be wrong. Sound
>    good?

I think it's sensible to just issue a warning if the HaaS cli tool is 
run as root at all - there isn't a legitimate use case for that.

>    When using sqlite, it might also be more user friendly to check
>    permissions on the DB using os.access() and print a warning if there is
>    an issue. Currently, the error is a lengthy stack trace ending in
>    something like this:
> OperationalError: (OperationalError) attempt to write a readonly database u'INSE
> RT INTO node (label, project_id, ipmi_host, ipmi_user, ipmi_pass) VALUES (?, ?,
> ?, ?, ?)' ...

It's probably cleaner to just catch the exception; I bet it's got enough 
info in it to come up with a nicer error message. This way we're not 
writing special case code for SQLite.

@gsilvis?

**Comment by zenhack** [comment]
I'm going to self-assign.
