### ISSUE TITLE
HaaS CLI should have a 'version' command

### ISSUE THREAD

**Issue by gsilvis** [CCI-MOC/hil#389]
It would print the version.

**Comment by SahilTikale** [comment]
A fix for this is generated under #425

**Comment by zenhack** [comment]
@SahilTikale, I'm assigning this to you, since you've already got a patch out for it. Apoorve asked me to give it to him, did you two coordinate something I don't know about? In any case, this should make it a little more clear what's going on.

**Comment by SahilTikale** [comment]
No, we did not coordinate anything related to this call. I am working on this and it is fine that you have assigned it to me. In future if I and Apoorve work on any part of HaaS together we will update you accordingly.

**Comment by naved001** [comment]
@shwsun and I would like to work on this issue.

**Comment by SahilTikale** [comment]
It requires changing the way we have implemented cli.
Wait for sometime. Once client library is over, you can start working on
this.

--Sahil

**Comment by shwsun** [comment]
@SahilTikale Yes, I just talked to Naved this morning, he can't start to work on this issue unless #617 and the click enhancement is done.

**Comment by xuhang57** [comment]
@naved001 I can work on this. Currently, HIL version is 0.2 right? Should I hardcode the version or there is a better way of handling this through automation?

**Comment by xuhang57** [comment]
@SahilTikale Can I take this? ;)

**Comment by naved001** [comment]
I am actually not sure myself how to do this because the HIL CLI and API server would be running on different machines. Which would mean getting the version from the hil server through an API? or would the CLI fetch it from wherever it was installed. What if we are using different  versions of the hil for cli and api server.

I don't have a clear thought regarding this. But you could come up with some proposal.

Also you wouldn't hardcode it, you would probably fetch it from `setup.py` 
This PR might be relevant. https://github.com/CCI-MOC/hil/pull/905

**Comment by xuhang57** [comment]
hmm, let's talk in person first then. I thought the cli and api are always come together.Or at least, the cli is calling the api so maybe I am wrong.

so we need to set the definition of the version of HIL cli ? And is that the same as the version release number on github?

The only way that i know is to hardcode the release version in the code base. Whenever you do a version upgrade, you need to make sure it is changed.

Or, if hil is a python package(I know it is), we can manage the version through pip so it doesn't have to be hardcoded. But we need to play it with pip and set up the version. Do you have the access to do that? 

@zenhack any thoughts?

**Comment by zenhack** [comment]
Either or both of the following would be reasonable:

1. A new subcommand on the `hil` tool that reports the version of *itself*. i.e., this does not talk to the server.
2. An API call that reports the version (or supported versions) of the server's *API*

Re: implementing (1), you can use the pkg_resources library to detect the installed version of a package, for example:

https://github.com/zenhack/simp_le/blob/0fc118de6c0fcad0e7a23a8e788a1e00995a1f5a/simp_le.py#L67

(2) would of course require versioning the API first; see #571.

What I do *not* think is a good idea is an API call to report the version of the HIL software running on the server. Clients shouldn't care about this, they should only care about what API is supported.

**Comment by xuhang57** [comment]
PR merged so close this now
