### ISSUE TITLE
switch driver model needs documentation

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#39]
Most of the assumptions behind the switch driver model are undocumented. This came to my attention when helping @rohgarg get up to speed for working on issue #27. We should actually write all of this down in an easy to understand way in an easy to find place. To start, here is an email I sent to @rohgarg in response to one of his questions:

```
Hey Rohan,

Several points of clarification:

* You should always be working from the devel branch - newapi is for a
  specific change unrelated to #27. (It's not the driver api it's
  talking about). What's on there was actually out of date; I just
  merged the changes to devel back into it.

* The haas.dell module on devel is representative of what a driver
  should look like.

* The cisco driver reflects the old driver api, which in the course of
  writing the new dell driver, I decided to clean up. You'll notice it
  expects some of the parameters to be comma-separated lists in the form
  of a string - yuck. If we wanted to use this driver again, we'd have
  to update it.

* The config file needs to contain both a general "which driver to use"
  setting, and possibly some driver specific options in their own
  section (for example a "switch dell" section).

  Things which might belong in the switch-specific section include
  "what is the" switch's ip address?", "who do I log in as?" and so
  forth. Depending on how we're interfacing with the switch these may
  not be the exact same parameters from one driver to another. As
  an example, the dell driver is adapted from an earlier driver
  that functioned similarly, but talked to the switch via serial,
  rather than telnet. This means, obviously, no ip address was
  needed. (and in fact no username/password either, if I recall).

As Zhaoliang said, the old dell driver *did* use SNMP, but it was
setting ports into general mode, which wasn't quite what we wanted.
Peter spent the better part of a day getting nowhere trying to figure
out how to set the ports to access mode via SNMP, after which we decided
it would make sense to just write a driver that talks to the console.
It's still doing all of the same things with Vlans and ports as what we
had agreed on previously, it just implements these via telnet and
console commands, rather than SNMP. As I mentioned before, I changed the
driver api in the course of writing that new driver.

Hope this helps,

-Ian
```

**Comment by henn** [comment]
This could make a good introductory issue to work on; working with either @gsilvis @zenhack or @lokI8

**Comment by zenhack** [comment]
Quoting henn (2015-04-10 14:38:42)
>    This could make a good introductory issue to work on; working with
>    either [1]@gsilvis [2]@zenhack or [3]@lokI8

There are some fairly detailed docstrings in `haas/drivers/__init__.py`.  
What do you think is missing?

**Comment by henn** [comment]
@zenhack, do you consider your issue to be resolved then?

I wasn't sure if you were advocating additional developer docs. Maybe we should toss a reference to this in [HACKING.rst](https://github.com/CCI-MOC/haas/blob/master/HACKING.rst)?

**Comment by zenhack** [comment]
Ack, totally missed that this was an existing issue; I saw it in my inbox and thought you'd opened a new one.

The error handling behavior is still unspecified, which I think is the only bit of this that still needs doing.

I'm actually going to remove the easy label -- the existing drivers don't really take errors into account at all, and figuring out what they should do when something goes wrong (which is a prereq for documenting it) will take a bit of thought.

**Comment by kylehogan** [comment]
What is the status on this? I looked through the docs and switch drivers and it doesn't seem to be resolved. Should it get moved to v2.0 milestone?

**Comment by zenhack** [comment]
Afaik, nothing has changed from the last time this was commented on; documentation is pretty good as far as it goes, but we just don't specify anything about error handling.

As to whether we should put it off until v2.0, last I was involved we still didn't having anything resembling a consensus on what the version numbers even meant. I'd been advocating for some version of [semver][1], which would mean v1.0 denotes API stabilization. A prereq for that is deciding what the API that we're stabilizing is: is it the HTTP Api, the driver interface or both?

If we're including the driver interface in our semver, then unless we're willing to flag 1.0 as still experimental, I think this needs to be fixed first. 2.0 would be the next opportunity, since it would probably necessitate API breakage.

Then there arises the question of how long are we planning on maintaing a major version? If we're not willing to drop 1.0 support as soon as 2.0 is out, then I don't want to commit us to a driver interface until we've actually got something reasonable, which right now we don't.

If we're *not* including the driver interface in the semver version, then this question is *completely* irrelevant, since we can stick it in whenever.

The above discussion all assumes folks are on-board with the whole semver thing, but I've had this conversation with @henn in the past and failed to convince him that it was the right/obvious thing to do.

I'd actually like to propose a moritorium on any use of milestones with a version number on them until we agree on what those numbers actually *mean*, and write it down.

**Comment by zenhack** [comment]
I'm going to close this; the only part that's still relevant is the bit that's described in #54.

Also, holy crap this issue is old. This is our oldest open issue. We have *more than one* issue that is over 2 and a half years old. I think I'm going to start periodically triaging the oldest of them, because wow.
