### ISSUE TITLE
Port for running HaaS server hard coded into rest.py

### ISSUE THREAD

**Issue by SahilTikale** [CCI-MOC/hil#399]
HaaS server fetches the information like which port to run on from the file rest.py ( /haas/moc/rest.py)
While looking around the source code along with Jason, we came across this line 

run_simple('127.0.0.1', 5000, wsgi_handler, use_debugger=debug, use_reloader=debug)

which states that the port is hard coded and we cannot use any other port to run a HaaS server. 

This is a problem if we wish to run multiple instances of HaaS server to test the recursive HaaS setup. 
Was wondering if this should be parameterized ?

**Comment by zenhack** [comment]
Quoting Sahil Tikale (2015-03-06 14:21:18)
>    Was wondering if this should be parameterized ?

Probably. Patches welcome, If I have some time I'll get to it, but no 
promises for a time frame.

-Ian

**Comment by apoorvemohan** [comment]
do we want to specify the port using a config file or pass it as a command line argument?

**Comment by zenhack** [comment]
Good question. I think a CLI argument might make more sense. @henn, @gsilvis, @lokI8, opinions?

**Comment by pns005** [comment]
It is quite typical to be able to specify configurable object such as port
number as a command line argument *and* from config. file.

Perhaps, start with command line argument. Once that works then can move on
to support config file especially if we anticipate many many customized
port numbers.

**Comment by apoorvemohan** [comment]
I thought so as-well. Submitted the changes for review (Opened pull request #429 ).

**Comment by zenhack** [comment]
Quoting pns005 (2015-05-18 22:15:10)

>    It is quite typical to be able to specify configurable object such as
>    port number as a command line argument *and* from config. file.
>    Perhaps, start with command line argument. Once that works then can
>    move on to support config file especially if we anticipate many 
>    many customized port numbers.

I would agree except that the `haas serve` command is just for 
development purposes --- this is bypassed entirely in a production 
setup, and you'd set the port in the webserver config.  This is mainly 
going to be useful when working on something like recursive haas, where 
you need to avoid collisions. I don't have a strong objection to adding 
a config file option though.

**Comment by apoorvemohan** [comment]
Just realized the I have not done exceptional handling for (1) if the user specifies port number outside 0-65535 range. (2) non numeric port number. The code will crash showing ugly stack trace. Please cancel the previous pull request.

**Comment by zenhack** [comment]
Quoting apoorvemohan (2015-05-19 17:16:42)

>    Just realized the I have not done exceptional handling for (1) if the
>    user specifies port number outside 0-65535 range. (2) non numeric port
>    number. The code will crash showing ugly stack trace. Please cancel the
>    previous pull request.

Good call (the cli, and HaaS generaly, already does way too little error 
checking, but we should start improving it, so thanks). I see you've 
already pushed some changes (and I've made some comments) -- there's no 
need to "cancel" the pr, it will update automatically as you continue to 
work on that branch.

-Ian

**Comment by matsuuran** [comment]
addressed in #429
