### ISSUE TITLE
Mechanism for expressing network driver capabilities

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#410]
For work like what @zenhack is doing in #408, it would be good to have a mechanism for registering the optional capabilities for drivers. One example would be for a driver to advertise its ability to do channels, where multiple networks can be communicated over a single NIC/port.

As HaaS grows and has more code & contributors, it may not always be feasible to support new features (like channels) in all existing drivers.

Other capabilities could include the bridging of networks between HaaS instances (#409), QoS options or enabling jumbo frames.

Updated:   
**Examples include:**
- Jumbo frames are per-switch on our Dell switches and per-port on our Ciscos (#755)
-  QoS (#384)
- Disabling STP (#779)
- DHCP/ARP Snooping (#471)
- Enabling the tagging of DHCP packets with the port number (from @okrieg or @pjd-nu)

**Comment by henn** [comment]
CC @naved001 @zenhack

**Comment by henn** [comment]
Examples include:
- Jumbo frames are per-switch on our Dell switches and per-port on our Ciscos
-  QOS
- Disabling STP (#779)
- DHCP/ARP Snooping (#471)
- Enabling the tagging of DHCP packets with the port number (from @okrieg or @pjd-nu)

**Comment by SahilTikale** [comment]
@shwsun @naved001 @Izhmash @zenhack 
We discussed this how do we wish to expose to the user, what different services HIL provides for a given switch. Currently switches are not exposed to the users. They only know about nic and networks. 
We think we should augment the one of the calls `show nic` or `show network` where we can list what other services HIL provides for that given switch.

**Comment by zenhack** [comment]
To clarify/expand a bit on @SahilTikale's summary:

* The obvious thing would be to just query the switch, but the switch topology is currently only exposed to admins.
* We've talked about wanting to expose topology to the users in the future; one that happens we should probably move this information there.
* We *can* report this information via the affected visible objects, i.e. networks and NICs
* There was some disagreement about whether networks or NICs made more sense. I think NICs make more sense; with networks you have the problem of possibly needing to do multi-switch queries to determine the answer to a question. @SahilTikale said he thought it was better to do it on the network. We didn't want to get bogged down with that argument during the meeting. @SahilTikale, do you want to make the case for doing it on the network here?

**Comment by SahilTikale** [comment]
@naved001 @Izhmash and I are in the meeting today. 
I gave some thought to our discussions last week and I agree that putting this as a part of `show_nic` makes more sense than `show_network`. But I have some more questions, I will add it to the thread here after the meeting.

**Comment by shwsun** [comment]
Sorry for the delay, was trapped into sth previously. Here are some more questions/thoughts:
1. I think exposing network topology is very important and seems very related, is that on our roadmap somewhere?
2. In the long run do we want to let admin make `network` with different functionalities beforehand? (s.t. users can choose a `network` with QoS, or a `network` with Jumbo frame?) My $0.02 here is that HIl is built for network admins, the focus would be: 1) have drivers implemented with functionalities s.t. admin can easily manipulate it, 2) users will get the slice of resource they want and go from there (only knowing what is going on inside the `network` is good enough).

Any other ideas?

**Comment by henn** [comment]
The first implementation of this will be #755.

Now that we have a decision, closing this out.

**Comment by zenhack** [comment]
I'm not sure I understand why this was closed? we've come to a consensus about what to do, but this still isn't done -- this should probably remain open until we've actually merged a solution.

**Comment by henn** [comment]
My suggestion is that:
* We have per-switch capabilities (like a giant ENUM)
* These capabilities are checked in api.py

That way, api.py doesn't need to do switch-specific logic; each switch's capabilities are exported in a generic manner.

For example, we could have a PER_PORT_JUMBO_FRAME setting, which is exported by each switch driver's get_capabilities(), and then checked in the api.py call for enable_jumbo_frames().

**Comment by naved001** [comment]
@henn @Izhmash and I discussed this again today. And we think that the following should solve this issue.

* Every switch driver will have a list called `capabilities` in the class. So it would look like 
`capabilities = ["require-native-network", "per-port-jumbo-frames"]`

* and then there'll be a method  `get_capabilities()` that returns a boolean if a capability exists or not by checking it in the list.

* an API that needs to test this, can call that method `switch.get_capabilities('require-native-network`) to ensure that the switch supports that method, and then proceed with the original request or error out.

* `show_node()` can be updated to show the capabilities they support.

**Comment by naved001** [comment]
#895 closes this
