### ISSUE TITLE
Better documentation for HIL consumers/end-users

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#411]
Currently, our [end-user/consumer documentation](https://github.com/CCI-MOC/haas/blob/master/docs/USING.rst) does not have any examples.

It would be good to improve this before our next release, including perhaps some scripts in the examples/ directory.

**Comment by zenhack** [comment]
The file you link to expressly refers to `examples/puppet_headnode`; we do have one example, which works. It is rather slapped together though.

**Comment by henn** [comment]
Ok - then we can mark this as easy :)

The documentation should be tied into the README

**Comment by zenhack** [comment]
I'd like to see a concrete list of actionable tasks for this issue; as it stands exactly what needs to be done is somewhat vague.

**Comment by henn** [comment]
Essentially, I was thinking of something that would show the basic operations of HaaS. Perhaps:
- [ ] Creates a project
- [ ] Allocates 2 nodes
- [ ] Creates 2 networks
- [ ] Attaches those networks to the nodes
- [ ] Creates a headnode that is attached to the PXE interfaces
- [ ] Resets the nodes
- [ ] (Bonus points for PXE'ing an OS onto the nodes from the same script)
- [ ] Tears everything down.

**Comment by zenhack** [comment]
Okay, I think that's a good checklist of things to have in an example somewhere. @gsilvis, @lokI8, thoughts?

**Comment by xuhang57** [comment]
@zenhack @naved001 So here we have a good list of examples we should come up with. This relates to: https://github.com/CCI-MOC/hil/issues/903, right? 

Basically, we will have both `README.md` and `Use HIL as a client` as the docs for HIL python client API documentation.

**Comment by naved001** [comment]
you are right, this is just how to use the HIL cli to do something useful. We can probably skip the headnode related call, and pxe booting an OS (that's not really what HIL does).

**Comment by xuhang57** [comment]
Thanks for confirming. So a updated list would be:

- [ ] Creates a project
- [ ] Allocates 2 nodes
- [ ] Creates 2 networks
- [ ] Attaches those networks to the nodes
- [ ] Resets the nodes

**Comment by zenhack** [comment]
Yeah, looks good to me. When we add the openvpn stuff we should also add examples for that (plus links to configuring the openvpn client).

**Comment by xuhang57** [comment]
PR merged. Closing this.
