### ISSUE TITLE
node_delete operation too slow

### ISSUE THREAD

**Issue by apoorvemohan** [CCI-MOC/hil#445]
The node_delete event operation is too slow. To delete even one node it takes around 60 seconds. After investigating and discussing with @zenhack it seems that this is due to the stop_console() being called from the code.

**Comment by zenhack** [comment]
I think we should address #417 head on before investing effort here --- deleting node is infrequent enough that I don't think we need a quick fix.

@gsilvis ?

**Comment by gsilvis** [comment]
I agree with @zenhack here.  (In fact, any sane solution to #417 will solve this immediately.)

**Comment by naved001** [comment]
see #1036
