### ISSUE TITLE
There needs to be a 'list_networks' command

### ISSUE THREAD

**Issue by gsilvis** [CCI-MOC/hil#453]
The exact semantics are up to debate, but there really should be /something/.  As it is, there's no way of finding the information out, so I'm calling this a bug.

**Comment by zenhack** [comment]
Quoting George Silvis, III (2015-07-10 15:49:03)

>    The exact semantics are up to debate, but there really should be
>    /something/. As it is, there's no way of finding the information out,
>    so I'm calling this a bug.

Yeah, I hit this earlier today. Would also be nice to be able to query 
what a (h)nic is attached to.

-Ian

**Comment by lokI8** [comment]
Or a physical nic. Would be nice to tell if one of the networks got detached from one of my nodes without going into the switch.

**Comment by zenhack** [comment]
Quoting Jonathan Bell (2015-07-15 14:36:59)

>    Or a physical nic. Would be nice to tell if one of the networks got
>    detached from one of my nodes without going into the switch.

I had been thinking in terms of a user figuring out what's connected to 
what network, but yeah, it would also be useful for administrators to be 
able to query what's attached physically.

**Comment by henn** [comment]
I just hit this- if you want to disconnect a NIC from some existing network, you have to know which network it is currently connected to satisfy `node_detach_network`. There is currently no way to do this without peeking in the DB or listing all of a project's networks and trying each possible one.

What do folks think about adding this information to `show_node`?

Instead of:

    $ haas show_node foo
    {"nics": [{"macaddr": "UNKNOWN", "label": "eth0"}], "name": "foo", "free": false}
we could have

    $ haas show_node foo
    {"nics": [{"macaddr": "UNKNOWN", "label": "eth0", "networks": [{"pxe", "vlan/native"}]}], "name": "foo", "free": false}

**Comment by zenhack** [comment]
Quoting henn (2015-07-23 01:20:33)

>    What do folks think about adding this information to show_node?
> 
>    Instead of:
> $ haas show_node foo
> {"nics": [{"macaddr": "UNKNOWN", "label": "eth0"}], "name": "foo", "free": false
> }
> 
>    we could have
> $ haas show_node foo
> {"nics": [{"macaddr": "UNKNOWN", "label": "eth0", "networks": [{"pxe", "vlan/nat
> ive"}]}], "name": "foo", "free": false}

This looks pretty reasonable to me (except of course the fact that 
you've got a syntax error :P).

-Ian

**Comment by henn** [comment]
@loki8 @gsilvis would `show_node` including this information satisfy your needs?

@zenhack syntax error?

**Comment by zenhack** [comment]
You've got `{"pxe", "vlan/native"}` rather than `{"pxe": "vlan/native"}`. Nothing major.

I think it would still be good to to be able to list what networks I have, in addition to the extra info in the `show_node` output.

**Comment by gsilvis** [comment]
We definitely need list_project_networks [which we already have, IIRC].  Either show_node or show_nic must show what networks the nic is attached to.  It might be nice for show_network to show the nics attached to it, as well.

**Comment by zenhack** [comment]
Quoting George Silvis, III (2015-07-24 12:50:56)

>    [which we already have, IIRC].

So we do! I think Jay's suggestion is complete enough then.

>     It might be nice for show_network to show the nics
>    attached to it, as well.

What should a show_network do on a public network?

**Comment by henn** [comment]
To summarize what we've discussed:
-  [ ] have show_node display networks
- [ ] have show_headnode display networks
- [ ] List public networks
- [ ] List all available networks (maybe admin-only?)

Any others? If so, please edit this post to add to the list.

**Comment by henn** [comment]
Closing this so that we can address public networks separately.
