### ISSUE TITLE
haas.errors.AllocationError should probably inherit from ServerError, Not APIError

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#461]
This isn't really the user's fault, and should be a 500-range error.

**Comment by naved001** [comment]
yeah. APIError returns 400 (Bad request) but resource exhaustion is not a users fault.

**Comment by zenhack** [comment]
Hm, then maybe we should be using something else on your vlan pr?

**Comment by naved001** [comment]
The name AllocationError sounded appropriate to me. I just dont think the error code is appropriate.

**Comment by zenhack** [comment]
Right, but if we're going to change it to 5xx, we should probably use something else for #823. Maybe BlockedError?

**Comment by naved001** [comment]
Cool. so in #823 I'll use BlockedError (code 409 = conflict ). But for this issue we should probably change AllocationError to some 500 level ServerError

**Comment by zenhack** [comment]
Yep.

**Comment by zenhack** [comment]
I'm going to go ahead and change this.
