### ISSUE TITLE
OBM driver for IPMI 1.x

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#475]
@gsilvis, @henn and I just had an in-person dicsussion re: supporting IPMI 1.x (prompted by the comments in #457). We're going to go ahead with dropping support in the core for now, but once the OBMs have been drivertized, we _may_ want to add this functionality back in. This is still TDB; for the record I'm against it, but we're deferring the discussion and recording it in this issues.

**Comment by naved001** [comment]
do we really need to support ancient hardware at this point? I remember upgrading the sun machines' IPMI to work with our current driver (see #694)

**Comment by zenhack** [comment]
I was against the idea when this issue was opened, and yeah, I think it's still not worth it, and we should close this. @henn, how do you feel about this these days?

**Comment by naved001** [comment]
@henn hasn't responded; I am closing this issue for now. Reopen it if you think this is pertinent.
