### ISSUE TITLE
Fix example / add test for dbinit.py

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#495]
#455 broke the example script used to create an example of a populated haas install.

This is really useful when developing and testing new code. Someone should update it so that it works with the latest haas.

**Comment by henn** [comment]
One step better: we should add a test that creates a local haas server and runs dbinit.py against it that is part of the Travis CI.

That way, any future changes to the API will also change the example script.

**Comment by naved001** [comment]
> One step better: we should integrate a test that creates a local haas server and runs dbinit.py against it. We could run this as part of our CI.

It's run as a part of [our CI now](https://github.com/CCI-MOC/hil/blob/master/ci/apache/run_integration_tests.sh#L15-L16) :D
