### ISSUE TITLE
show_network() should display connected nodes

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#496]
Currently, one has to dig through the DB or iterate through every node to figure out what's connected to a network.

This is needed for times like these:

```
$ haas network_delete random-network
Unexpected status code: 409
Response text:
{"msg": "Network still connected to nodes", "type": "BlockedError"}
```

If we showed connected nodes (+ maybe the channel, NIC,  switch and port name), this would allow all sorts of configuration goodness.
Maybe we could just include the output of `show_node()` for each node?

**Comment by henn** [comment]
Hey @xuhang57. As you are doing your query work, would you mind including this?

Thanks!

**Comment by jmcadden** [comment]
I've also notice this to be an active issue with no apparent work-around (other than guessing). This information is critical to the project_detach_node command, which is a prerequisite for project_detach_node.

**Comment by kylehogan** [comment]
This will be useful (necessary?) for the many to many project:network relation to work. 

e.g. to remove a project's access to the network all nodes on that project would first need to be disconnected from the network. For this to happen it needs to be possible for the network creator to see which nodes are connected to the network.

What is the status of this? I had been planning to include it as part of #545
