### ISSUE TITLE
api returns to user when nic is busy

### ISSUE THREAD

**Issue by jmcadden** [CCI-MOC/hil#510]
Consecutive "node_detach_network" requests to the client api can result in a fatal "nic is busy" error. This error seems unnecessary for the user, and the behavior incorrect. Ideally, the api would block until the existing task is finished before continuing. 

```
>$ haas node_detach_network cisco-44 enp130s0f0 net0

>$ haas node_detach_network cisco-44 enp130s0f0 net1
Unexpected status code: 409
Response text:
{"msg": "A networking operation is already active on the nic.", "type": "BlockedError"
```

**Comment by xuhang57** [comment]
PR merged. Close this now. Please reopen if necessary
