### ISSUE TITLE
Introduce bash completion for HaaS

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#515]
After incorporating argparse (#431), we should look at adding bash completion in the default install scripts since remembering all of the subcommands can be a little tedious.

It looks like there are 2 packages that can do this easily:
- [Argcomplete](https://argcomplete.readthedocs.org/en/latest)
- [Python-selfcompletion](https://github.com/dbarnett/python-selfcompletion)

[This stackoverflow](https://stackoverflow.com/questions/20838284/how-can-i-provide-tab-completions-to-fish-shell-from-my-own-script) also has some info.

**Comment by shwsun** [comment]
I think click is able to do these bash completions as well, see. [nfoi](http://click.pocoo.org/6/bashcomplete/). This one will solve itself if we decide to go down that path. @matsuuran what do you think?

**Comment by matsuuran** [comment]
@shwsun definitely and it would make life way more convenient.  Are we still waiting on a PR?

**Comment by naved001** [comment]
I think bash completion can be introduced once we start using argparse which has it's issue here #431. So should we close this and keep just one issue to track that?

**Comment by zenhack** [comment]
I certainly think we should handle that one first. It will be pretty easy once we do:

https://stackoverflow.com/questions/14597466/custom-tab-completion-in-python-argparse.

I'm fine with tacking it on to that issue.
