### ISSUE TITLE
cli tests erroneously report 0% test coverage.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#516]
This happens because we actually launch the cli as a separate process, but it would nonetheless be nice to get the stats on that.

**Comment by xuhang57** [comment]
do we have any code coverage tool to test the code coverage? I don't find it in the ci I believe. Maybe we can use https://coveralls.io/?

**Comment by zenhack** [comment]
We have pytest-cov set up for code coverage, though I don't think it runs automatically in CI. That would be a nice addition (feel free to open a separate issue), but what this issue is about is that the way the coverage tool works, it doesn't track coverage from forked processes, so when we call the command line tool from inside of a test, it doesn't notice that we've executed code inside the cli tool.

**Comment by xuhang57** [comment]
so we need someone to send a PR for enabling `pytest-cov` in CI right?

**Comment by zenhack** [comment]
Hm, the relevant bits in setup.cfg are actually in there commented out. Commit 14d6be62 seems to be the patch that removed it. The commit message suggests it was causing failures? @SahilTikale, that commit has your name on it, do you remember the details?

The other thing is, it would still be nice to integrate with GitHub somehow, so we can get the results without going and looking at the travis log.

**Comment by xuhang57** [comment]
coverall has a bot can post the coverage report as a comment in PR. See this example:https://github.com/CCI-MOC/giji-backend/pull/31

**Comment by zenhack** [comment]
I'm fine with adding coveralls to the CI.

**Comment by xuhang57** [comment]
@zenhack I don't have the access to enable it. I believe only the admins could. Maybe one of the admins could add it.

**Comment by zenhack** [comment]
I don't think I have admin access to this repository either. @naved001?

**Comment by naved001** [comment]
both of you are admins now. Sorry I've been busy with some infrastructure stuff, will get back to HIL soon enough.

**Comment by xuhang57** [comment]
hmm, it turns out being an admin on the repo is not good enough. You need to be an organization admin to enable it from the `coveralls.io`. For some reasons, I cannot search coverall from the settings.

ping @pns005 @knikolla @okrieg @pjd-nu
