### ISSUE TITLE
Enhance Travis CI testing with virtual OBMs and switches

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#518]
Right now, we just run the unit tests using the defaults (sqlite I presume). We should also test postgres as well as see if the deployment tests can be made to use `None` Obm or Switch types.

Links to Travis CI documentation on:
- [Postgres](https://docs.travis-ci.com/user/using-postgresql/)
- [Python projects](https://docs.travis-ci.com/user/languages/python)

**Comment by henn** [comment]
Per @zenhack's comment in #90:
> We should be running tests/stress.py as well.

**Comment by henn** [comment]
The first concern (postgres support) was addressed in  #561 

The second (deployment tests) is being worked on right now by @SahilTikale as part of his OVS work. Assigning this to him.

**Comment by zenhack** [comment]
I think we actually have the deployment tests running in travis now we can probably close this

**Comment by henn** [comment]
@SahilTikale is working on connecting VMs with OVS in a VM. We could potentially deploy that to Travis as a sort of end-to-end deployment test.

We could track that with this issue or open a new one (either is fine by me).

**Comment by xuhang57** [comment]
close this now.
