### ISSUE TITLE
Enable a network to be accessed from multiple projects

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#520]
Currently, in api.py, we do an access check to see if a node's project is allowed to access a network:

```python
def node_connect_network(node, nic, network, channel=None):
    if (network.access is not None) and (network.access is not project):
        raise ProjectMismatchError("Project does not have access to given network.")
```

Given a current use case (Bare Metal Imaging), we would like a node (or headnode) in one project to be given access to a user's network in another.

In discussing this with @kylehogan, @SahilTikale and @gsilvis, it sounds like making network.access a list (thus, a many<->many relation) should do this.

There would also need to be an API to add an additional project to a network. This could look like:
```
PUT /network/<net>/access/<other_project>
DELETE /network/<net>/access/<other_project>
```

**Comment by henn** [comment]
@zenhack I don't think this will affect #491, but wanted to let you know just in case you can see an interaction.

**Comment by zenhack** [comment]
@henn, thanks. I don't think it affects anything I'm working on now, though obviously some of the relevant bits will have to be changed once you actually implement this.

**Comment by henn** [comment]
Thought it might be helpful to point this documentation out (which will need to be updated): https://github.com/CCI-MOC/haas/blob/master/docs/networks.md

**Comment by gsilvis** [comment]
Fixed by Network ACLs
