### ISSUE TITLE
In Hacking.rst, headnode_create also requires base_img argument

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/hil#523]
In the `Hacking.rst` developer document, the `headnode_create` command also requires the base_img as an argument. 

```
haas headnode_create hn proj
```

It should be 

```
haas headnode_create hn proj img1
```

**Comment by shwsun** [comment]
Same issue in ``doc/consistency-model.md``, ``docs/apidesc.md``, ``docs/rest_api.md``. I thought the documentation may have to be refactored afterwards, before v0.2.

**Comment by henn** [comment]
@shwsun: Would you be interested in taking this on? Might be a good way to get used to the system before the meatier items.

**Comment by shwsun** [comment]
@henn Sure. I will fix these outdated doc ASAP. 

Also I would propose that maybe we should refactor the documentation somehow, i.e. installation/HACKING should cover all the things that user/developer need. rest_api or apidesc only appears as reference, details won't pop up unless someone is looking for them.

**Comment by henn** [comment]
Awesome. Thanks!

Please check with @SahilTikale, since he's refactoring some of the
developer-related docs.

**Comment by naved001** [comment]
closing this because #653 got merged
