### ISSUE TITLE
API call to list extensions active with HaaS

### ISSUE THREAD

**Issue by SahilTikale** [CCI-MOC/hil#529]
We need an API call to list the which extensions are available for a given HaaS installation. 

For eg.
User should be able to run a command and inquire which obm driver is active 
or which switch drivers are available. 

Users will be mostly system administrators managing HaaS.

**Comment by Izhmash** [comment]
Would one API call that lists every extension suffice, or should there be an argument for the type of extension (auth, switches, etc.) to be described?

**Comment by naved001** [comment]
I think an API that lists everything should suffice. Just package the response in a way such that it's easier to get the stuff we need. 

> should there be an argument for the type of extension (auth, switches, etc.) to be described

you can do that in the CLI

**Comment by Izhmash** [comment]
I have an implementation of this finished, going to wait until the name change to present it.

**Comment by naved001** [comment]
#820 fixes this.
