### ISSUE TITLE
docs/rest_api.md is out of sync with implementation

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#536]
People have been changing the API without changing the docs. We need to get these back in sync, and we need to make sure this doesn't happen again.

The file `docs/rest_api.md` contains a detailed description of the API. that description _MUST_ be updated with _EVERY_ change to the API.

Submitters: If you change the API, change the docs.

Reviewers: Do not **under any circumstances** merge a patch which changes the API without updating the docs.

@SahilTikale, in an attempt to keep this _really important_ issue from just getting forgotten about, I'm assigning this to you. Make sure the recent changes to the API are documented. At least some of the changes in question are yours, but I haven't done a full audit. Submit a pr with the documentation updates. I'd be interested in being asked to review that patch.

A few of the API changes themselves seem somewhat dubious, but I don't really have the time to pick through them all right now.

//cc @henn, @gsilvis, @lokI8, @SahilTikale, @knikolla, @okrieg, @pjd-nu, @pns005

**Comment by zenhack** [comment]
Also, for each of these documentation sync issues we find, we should make sure there's a test! It shouldn't be possible to change the output of an API call without causing test failures.

**Comment by SahilTikale** [comment]
I was not aware of this.  Will take care of it in my pull requests and will monitor for all other pull requests that involve changing API calls.

**Comment by zenhack** [comment]
@SahilTikale, thanks. Sorry to be so stern about it.

I suspect you're not the only one who's made this mistake; it would be good to go through and audit the changes that have been made, since there's probably other drift. Looking at the history for `api.py` might be a good place to start, maybe going back through september or so, which is when I left.

**Comment by zenhack** [comment]
Apparently I'm guilty as well (#537). Oops.

Glad people are tackling this. I'd like to help with review, but since I'm billing you guys by the hour for that I feel like folks have to explicitly ask me to first. Ping me if you need a pair of eyes on these things.

**Comment by SahilTikale** [comment]
knock knock @vsemp

**Comment by SahilTikale** [comment]
any updates on this @vsemp

**Comment by vsemp** [comment]
I didn't see any inconsistent arguments or completely incorrect descriptions.

There the following potential inconsistencies of rest_api.md with api.py:
- Console code doesn't have documentation
- list_active_extensions from "API Extensions" is in api.py while other "API Extensions" are not

**Comment by vsemp** [comment]
I suggest writing a separate function that checks some common access requirements.

**Here is one example:**

> Authorization requirements:
> If the owner is a project, access to that project is required.
> Otherwise, administrative access is required.

`    if network/node.owner is None:
        auth_backend.require_admin()
    else:
        auth_backend.require_project_access(network.owner)`

This piece of code is used in multiple places:
https://github.com/vsemp/hil/blob/12489961c975a7d0d0ec4328a59f5457d5b0103c/hil/api.py#L851
https://github.com/vsemp/hil/blob/12489961c975a7d0d0ec4328a59f5457d5b0103c/hil/api.py#L153
https://github.com/vsemp/hil/blob/12489961c975a7d0d0ec4328a59f5457d5b0103c/hil/api.py#L264
https://github.com/vsemp/hil/blob/12489961c975a7d0d0ec4328a59f5457d5b0103c/hil/api.py#L276
https://github.com/vsemp/hil/blob/12489961c975a7d0d0ec4328a59f5457d5b0103c/hil/api.py#L290

**Comment by zenhack** [comment]
Good spot on that pattern; definitely worth factoring that out.

Re: the console stuff: my inclination is to leave that for now, as we're re-designing that anyway

`list_active_extensions` should be moved out of the API Extensions section; want to add that to your PR?

**Comment by vsemp** [comment]
OK. I'll do that.

**Comment by naved001** [comment]
#886 and #902 fix this.
