### ISSUE TITLE
Add PEP8 compliance test to standard tests

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#539]
HaaS should run PEP8 compliance tests as part of the automated checks.

https://pypi.python.org/pypi/pytest-pep8

**Comment by zenhack** [comment]
+1

**Comment by zenhack** [comment]
That looks absolutely trivial to set up. I will point out it's going to flag an absurd amount of issues at first; I've got vim's python-mode set up, and there's a *lot* of stuff to fix. I just hit a spot in the code where someone put tab characters though; we should have someone do this sooner rather than later.

while on the topic, @SahilTikale, the tabs appear to be your handywork, as well as a bunch of trailing whitespace that my editor fixed for me. Please be more careful. For folks using vim:

<https://github.com/klen/python-mode>

**Comment by henn** [comment]
Agreed- the time-consuming part of this will be the refactoring necessary to get the pool so that it passes the first time.

**Comment by zenhack** [comment]
One thing we could do is just tune it to ignore most problems for the first pass, and incrementally take things off the ignore list/fix them.

**Comment by zenhack** [comment]
I'll suggest we set it to egnore E221, which is "multiple spaces before operator." We purposefully do this to line up columns in the model declarations.

**Comment by gsilvis** [comment]
+1 for doing this as soon as practically possible

**Comment by henn** [comment]
Some great suggestions in #613.

**Comment by shwsun** [comment]
(ideas from HIL meeting)
@SahilTikale and I kind of agree that programmer should make sure their part is properly done before ``git commit``. So either follow pep8 and pep257 while coding or programmers can choose to use some flycheck or format tools to help. 

For travis tests, the next step perhaps to be removing ``stress.py`` test to save time, and add these pep8 & pep257 tests. @matsuuran will work on this.

**Comment by zenhack** [comment]
Quoting (Jethro) Shuwen Sun (2016-07-12 13:25:45)

>    (ideas from HIL meeting)
>    @SahilTikale and I kind of agree that programmer should make sure
>    their part is properly done before git commit. So either follow pep8
>    and pep257 while coding or programmers can choose to use some flycheck
>    or format tools to help.

Agree. Of course, they should also be running the test suite, but we
have travis anyway (and it's not just running the "hard to configure"
tests).

> For travis tests, the next step perhaps to be removing stress.py
> test to save time

We should *not* do this:

1. It's a regression test, it's there for a reason.
2. Last I looked it wasn't actually that slow. Measure before you
   optimize.

It is perhaps badly named; it was meant to test for a specific resource
leak that we ran into in production, but it isn't terribly intense.

> and add these pep8 & pep257 tests. @matsuuran will work on this.

Great, as long as we have someone assigned.

**Comment by matsuuran** [comment]
@henn @zenhack @SahilTikale @shwsun @gsilvis 

How strict do we want to be with the length of lines.  Cut everything at 79, or should we be a little more flexible?

**Comment by zenhack** [comment]
Good question.

I know there are at least a few spots in the code where we've got string
literals that just will not fit on any reasonable line length while
staying readable. I'm thinking specifically of the tests @knikolla wrote
for the brocade driver.

Given that, I don't how strict we can be. Do the tools we're looking at
give us a way to flag a piece of code as "ignore this?" e.g. with yapf
you can put in a comment

    # yapf: disable

and it will skip that bit of the code.

If so, we can use that for pathological cases like this. If not I'm not
sure what the thing to do is.

-Ian

**Comment by shwsun** [comment]
``pep8`` suggests normal line length of code to be 79 and docstring to 72. For some exception like @zenhack pointed out, I think it would be fine to keep it longer. And for that bit of code I guess python already have some way to suppress the warning.

**Comment by zenhack** [comment]
Quoting (Jethro) Shuwen Sun (2016-07-13 15:49:28)

>    pep8 suggests normal line length of code to be 79 and docstring to 72.
>    For some exception like @zenhack pointed out, I think it would be
>    fine to keep it longer. And for that bit of code I guess python already
>    have some way to suppress the warning.

My inclination is to just do 79 char lines. This is what vim's
python-mode checks for, and if you've got docstrings on methods in
classes they're going to be indented 8 spaces to start with, so 72
docstring chars maps to 80 total. I'm fine just truncating that to 79.

The implementer will have to add appropriate annotations to the existing
exceptions for the tests to pass, so we'll have a solution when this
goes in.

Sounds like we have a plan.

**Comment by matsuuran** [comment]
@zenhack @henn @gsilvis @shwsun 
I found that the only the only way to have pytest-pep8 inline ignore is to use `  # noqa` after the line.  I'm not a huge fan of how it looks but just wanted to get your guys thoughts and see if you knew/heard of any magic

**Comment by zenhack** [comment]
In that case, we could just pick a length and be fairly strict about it, and put `# noqa` only on things like the tests I mentioned where you pretty much *can't* restrict the line length.

**Comment by shwsun** [comment]
Agree.

**Comment by henn** [comment]
I'm happy with 79 everywhere.

One other thought -- if it's too much work to initially bring the entire code base into pep8, we could list basically all of the files you couldn't get to as exceptions [in the setup](https://pypi.python.org/pypi/pytest-pep8), then:

1. New files would be checked
2. Require anyone changing making changes in other files to bring them into pep8 compliance.

**Comment by matsuuran** [comment]
added in #628 and fixed in #651
