### ISSUE TITLE
Check for well formed port names on registration

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#54]
We're making use of pexpect to ensure the state of the shell is what we think it is, but if pexpect should throw an exception, it will crash the HaaS. This shouldn't be possible; we should be catching the exception somewhere.

**Comment by henn** [comment]
I've run into this, specifically when the port names are entered incorrectly. We should address this for 0.2

**Comment by henn** [comment]
Gold star if you can catch my specific error and report something like "Check that port names agree with the switch"

**Comment by zenhack** [comment]
@henn I think the right approach to port names would be to check them on the way in - there's no reason the driver can't know about their format.

Obviously we still need to do error handling for the general case.

**Comment by matsuuran** [comment]
@zenhack @henn  I've been googling a bit to see if I can find a way to ask the switch for a list of its port names so that we can check to see if the port they provided is completely valid.  I've had no luck, just wanted to see if: 
 - either of you knew how to ask the switch for its port names?
 - is it an okay idea?

**Comment by matsuuran** [comment]
@shwsun @naved001 do you know the answer to my question above?

**Comment by zenhack** [comment]
I think what we'd been discussing was validating the /format/ of the port name. e.g. on the powerconnects, you have things like gi1/0/23; I believe @henn was talking about the situation where someone accidentally types e.g. gk1/0/23; we should be able to inspect this when the API call is made without interacting with the switch.

What the original issue is about though, is that we just don't handle communication failures with the switch *at all.* If a connection to the switch breaks, pexpect will throw an exception, which is currently not handled *anywhere* so the daemon will just crash until a sysadmin goes and restarts it.

At a minimum we ought to add a try/except at some appropriate level, which cleans up state and goes back to trying to process `NetworkingAction`s, ideally with some kind of exponential backoff.

Note that there *are* still things an admin can do to introduce persistent failures, e.g. if an admin mis-types the port as gi1/2/23 and that particular port doesn't exist, we don't currently have a way of detecting that and handling that. This is at least something that only an admn can do though.

Dealing with errors in the network daemon is hard because because we don't currently have a way for it to communicate any information to the user. That's probably a more general issue that needs addressing.

**Comment by henn** [comment]
@matsuuran - do you think you could lead the discussion on this one?

**Comment by matsuuran** [comment]
@henn what do you mean by lead discussion?  I have a branch somewhere that has most of this figured out and could probably knock it out after apply networking is closed

**Comment by henn** [comment]
@matsuuran - I meant making sure everyone agreed on the solution to avoid unnecessary coding. If you have a PR, we could discuss it there too!

**Comment by henn** [comment]
@zenhack - since the NetworkingAction queue is serialized, an error processing one action should mean that we can't/shouldn't process other things. With systemd integration, we now have a way of capturing the stack trace via the journal or `systemctl status haas_network`.

Having something that checked the validity of a port name (by doing a `show interfaces` or something like that) would help.

I think repeating the request would only make sense for transient failures. I'm not sure how we'd bubble the errors back to the user. Maybe via the status API?

**Comment by zenhack** [comment]
@SahilTikale and I had a conversation about the status API today. I think that's the right way to go about reporting errors, but he's planning to have a more detailed proposal written up soonish, so let's talk about it in that context.

**Comment by naved001** [comment]
> @zenhack: I think the right approach to port names would be to check them on the way in - there's no reason the driver can't know about their format.

I am fine with this approach. 

> @henn: Having something that checked the validity of a port name (by doing a show interfaces or something like that) would help.
> @matsuuran: I've been googling a bit to see if I can find a way to ask the switch for a list of its port names so that we can check to see if the port they provided is completely valid.



I have been playing around with the switches lately. 
For the nexus switch, we can do `show interfaces switchport |grep Name` that would return a multi-line string with names of all the ports. Something like this
```
switch-name# show interface switchport |grep Name
Name: Ethernet1/1
Name: Ethernet1/2
Name: Ethernet1/3
Name: Ethernet1/4
.....
```

For the dell, we can do `show interfaces status` (more info, but faster) or `show interfaces description` (less info, but for some odd reason slightly slower). and this is how the output looks like. 
```
console# show interfaces description 
Port      Description
-------   -----------
gi1/0/1   
gi1/0/2   hack-n--hil switch
gi1/0/3   hack-n-hil IPMI
and so on
```
we could then use some fancy regex/string parsing to get the port names. 

All this is slightly unrelated to the original issue this. This only fixes one of the things that could cause unexpected errors in pexpect.  @matsuuran are you working on this issue at the moment?

**Comment by henn** [comment]
One other option for validating ports would be something like `show int <int_name>`, and see if there's an error.

**Comment by henn** [comment]
Let's make this issue about validating ports, and make another one about the more general handling of errors.

To be honest, crashing might be the best we can do until the status API comes around, as the networking action queue is there to ensure things don't happen out of order.

**Comment by SahilTikale** [comment]
Blocked on #805

**Comment by naved001** [comment]
#816 fixes this
