### ISSUE TITLE
API documentation should be in rest_api.md

### ISSUE THREAD

**Issue by kylehogan** [CCI-MOC/hil#543]
API documentation currently duplicated across api.py and rest_api.md. All documentation for the API should be in rest_api.md

Need to move documentation for API calls from api.py to rest_api.md

**Comment by xuhang57** [comment]
@kylehogan  Not sure if this is done. By documentation for API calls from api.py, do you mean the docs string under the name of each metho in api.py?

**Comment by kylehogan** [comment]
Yes, if I am remembering correctly I made this while we were discussing it during group meeting and the consensus was that there should be only short descriptions in api.py while the bulk of the information should be in rest_api.md

I think what was happening was that information was getting duplicated across both locations and that the length of the descriptions within api.py was becoming too much.

**Comment by knikolla** [comment]
Fixed by #793
