### ISSUE TITLE
Need API call for listing switches 

### ISSUE THREAD

**Issue by SahilTikale** [CCI-MOC/hil#550]
Currently there is no way to tell which switches are registered with HaaS.
Considering HaaS supports a multi-switch environment and that the api calls for port operations require <switchname> it will be helpful if we have a call to list the names of the switches registered with HaaS

**Comment by xuhang57** [comment]
Is someone working on this right now? If no one, I would like to do it. @SahilTikale

**Comment by henn** [comment]
Fixed by #569
