### ISSUE TITLE
show_switch API call

### ISSUE THREAD

**Issue by gsilvis** [CCI-MOC/hil#572]
This needs to show details of a switch.  Since different switches have different details, this will require support from the switch backend---probably another function call in the plugin API there.

**Comment by xuhang57** [comment]
So, along with #550, we also need a show_switch API call for HaaS. Not sure if anyone working on these two calls? If not, I could work on them. @SahilTikale

**Comment by kylehogan** [comment]
#550 handles both of them. there is also a show_switch implementation in #567

**Comment by xuhang57** [comment]
Thanks for pointing it out. @kylehogan

**Comment by shwsun** [comment]
#658 solved this, closing
