### ISSUE TITLE
Build errors from other Linux distros(Arch, Ubuntu)

### ISSUE THREAD

**Issue by shwsun** [CCI-MOC/hil#579]
Clearly I got two kind of errors mostly when I went through the building logs.

**1.  "OperationError: unable to open database"**

This happened both with CentOS and Ubuntu, solved by manually created the haas.db

[build logs from Ubuntu](https://gist.github.com/shwsun/a9bbcdbfb8b623fa3e8061ee81610e95)

**2. Error due to Python3 as the default python version**

Although I managed to setup virtualenv with python2, it appears that I still can't not get rid of it. Maybe developers already figure out how to avoid it, but somehow I failed to find it in the repo.

[build logs from Arch](https://gist.github.com/shwsun/8edcaadd879955303c94bc0041e7cc76)

@SahilTikale I would be happy to test if you have made changes.

**Comment by shwsun** [comment]
I tested and hacked the haas repo on Arch. Things are working fine right now.

**Comment by shwsun** [comment]
#592 will be good enough to solve any problem during HIL setting up. We can close it .

**Comment by naved001** [comment]
> #592 will be good enough to solve any problem during HIL setting up. We can close it .

Closing it then.
