### ISSUE TITLE
Need to validate "network_id"

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#584]
running `haas network_create foo admin '' yes` creates a public network `foo`with a VLAN-id of `yes`.

We should validate that the VLAN id is an integer

**Comment by gsilvis** [comment]
One option is:  Add a method to the NetworkAllocator class that checks for validity, and call that.

**Comment by gsilvis** [comment]
(Note that the null backend, in particular, uses UUIDs)

**Comment by naved001** [comment]
I would like to work on this issue after we decide what type of VLAN-ID is considered valid.

**Comment by naved001** [comment]
Here's a PR #670  that addresses this issue.

**Comment by gsilvis** [comment]
Fixed by #670
