### ISSUE TITLE
Migration docs: be more explicit re: setting/not setting down_revision

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#589]
The migrations doc says to change it to None only for new extensions, not for haas core. This is correct, but they're not very explicit about *not* changing this for existing extensions and/or haas core. Per the discussions in #554, this is likely to be misinterpreted. We should change it to be more explicit that this should be left-alone when not adding a new extension.

//cc @kylehogan, @henn

**Comment by zenhack** [comment]
@kylehogan, I included this in the pr I sent you, so once #554 gets merged, we can close this.

**Comment by matsuuran** [comment]
@zenhack I've been noticing there are a several issues that are still open, is it okay if I just do a little house keeping and close them?

**Comment by zenhack** [comment]
If they're obviously fixed, go for it. Just leave a comment explaining why you're closing. I'll take care of this one.
