### ISSUE TITLE
Serial console fixes for basic functionality

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#593]
We need to:

1) Document in the deployment guide that, at least on some platforms, one needs to first "enable" serial over LAN by running:

```
ipmitool -H <host-ip> -U <user> -P <pass> -I lanplus sol set enabled true
```

2) Introduce a script to create the console log directory (currently /var/run/haas_console_logs), owned by `haas_user`

3) If easy & possible, return an error to the user if the `ipmitool` call from `haas start_console` fails immediately and tell the user to contact their admin, rather than just showing an empty console buffer.

**Comment by naved001** [comment]
All this is now handled by OBMd
