### ISSUE TITLE
Project backends

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/hil#595]
Currently, we have an auth backend which does authentication and user/project assignment. In the eventuality that we want to have an Identity Provider (Keystone, or something else) do authentication and authorization for us, this is not enough and we must also offload all the project related logic to it.

In the Keystone example: We would be sending API calls to it for the list of projects, creating projects, deleting projects, assigning users to projects, etc. Currently HaaS assumes that there will be a project table with all this information, and it's a very strong assumption since it enforces a foreign key constraint.

To enable the use case above that assumption must be relaxed and an abstraction for projects created.

**Comment by henn** [comment]
Kristi- how do the OpenStack code bases handle projects?

For example, do nova and cinder have their own Project table that they reference from others? If so, how do they manage the life cycle of those objects?

**Comment by knikolla** [comment]
Nothing besides Keystone has a 'projects' table. The other services like nova and cinder only use (and care) about the project ID. That project ID comes from the scoped token and the project_id field in tables references it.

**Comment by xuhang57** [comment]
PR merged. Close this now. Please reopen if necessary
