### ISSUE TITLE
It is possible to have duplicate entries depicting same relation in database

### ISSUE THREAD

**Issue by SahilTikale** [CCI-MOC/hil#599]
I was trying to connect a nic to a network, that did not work as intended.

While examining the database I came across this.

```
sqlite> select * from network_attachment;
id | nic_id | network_id| channel
1|2|1|vlan/native
2|2|1|vlan/native
```

This should not happen. 
Working on recreating this error. 

While I tried running `node_detach_network`
it deleted both the rows.

**Comment by henn** [comment]
That should've been prevented by this code in haas/api.py's `node_connect_network`:
```python
    if _have_attachment(nic, model.NetworkAttachment.network == network):
        raise BlockedError("The network is already attached to the nic.")
```

**Comment by naved001** [comment]
@SahilTikale Can you reproduce this?

**Comment by naved001** [comment]
as per @henn's comment, this should not happen. 

@SahilTikale ping.

**Comment by naved001** [comment]
closing this for now, please reopen if you want to discuss this.
