### ISSUE TITLE
Change the name in the source: s/haas/hil/

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#602]
When I tried this when we were talking about changing the name to oil, it was pretty much _just_ a find and replace, though you need to make sure you get the handful of different capitalizations. Took like 2 minutes.

**Comment by shwsun** [comment]
This will have to be done before the camera ready ddl of the SoCC paper. 

@henn I think we should send out an email to notify the team s.t. people got PRs hanging need to push themselves.

**Comment by henn** [comment]
FYI - I'm trying to work on this in my branch, https://github.com/henn/hil/commits/rename
Am hitting postgres DB connection issues.

Related to #805

**Comment by henn** [comment]
FYI - We're still getting some issues with the rename.

[[Full output](https://gist.github.com/henn/068dabca855cb742f168f2f4dd331172)]

Abbreviated:

> $ sh -e ci/run_unit_tests.sh
> [...]
> tests/unit/hil_auth.py .
> 
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> 
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
> 
> The build has been terminated

**Comment by naved001** [comment]
Just spitballing here; how about we disable the tests we think might cause problems, and then enable them one at a time to figure out what test(s) fail the build. That should help us narrow it down at least. 

Actually, how about we disable the tests  that we know are passing at the moment (on your personal branch) to save some time on the builds and directly run the problem tests.

**Comment by zenhack** [comment]
Let's try to keep the discussion on #805; Per my comment there I already narrowed it down to the migration tests, and the DB hanging issue; I think if we keep splitting the conversation we're going to spend more time going in circles.

**Comment by zenhack** [comment]
Also, I can reproduce the problem with a local postgres, so a full travis run isn't totally necessary anyhow.

**Comment by SahilTikale** [comment]
@zenhack the issue to be renaming of branches in alembic.  He will be working on it today and will report the outcome soon.

**Comment by SahilTikale** [comment]
#805 closes this.
