### ISSUE TITLE
Need list_port() + show_port()

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#605]
Currently, we have list_{projects/nodes,...}. To help the admin, we also need list_port and show_port.

We should also include the port in `show_node`.

All of this should only be available for admins, since regular users don't manage ports.

**Comment by shwsun** [comment]
Since I am working on #567 and show_port() is already implemented by @kylehogan . I will take list_port() as well.

**Comment by henn** [comment]
Addressed by #767
