### ISSUE TITLE
PEP8 testing

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/hil#613]
How do people feel about integrating PEP8 testing into our CI with the `flake8` package? We can start with pretty relaxed rules and only follow a few of the PEP8 stuff and gradually move from there.

More info [here](https://flake8.readthedocs.io/en/latest/)

**Comment by henn** [comment]
+1

The hard part is doing the work to make us pass initially or of the
increasingly strict rules.

How does that compare to
[pytest-pep8](https://pypi.python.org/pypi/pytest-pep8)?

**Comment by knikolla** [comment]
I don't know how they compare. Since we're using pytest, might make sense to go with pytest-pep8. I mentioned flake8 because that's the one I know and OpenStack uses.

**Comment by shwsun** [comment]
I dig a little deeper. Looks like Openstack guys trying to not only follow the pep8 Style guide for python, but also cover [Openstack Style Guidelines](http://docs.openstack.org/developer/hacking/). I guess this makes the style more strictly defined and cause less trouble for openstack community. They also have a [tool](https://github.com/openstack-dev/hacking) developed for it.

I feel that integrating PEP8 with flake8 is fine as long as it wont consume too much time.

**Comment by knikolla** [comment]
@shwsun they have flake8 plugins for their style check. We don't really need that. Flake8 in itself without any plugins just checks for pep8, like pytest-pep8. 

Since we are already using pytest, once my integration testing PR goes in, I'll make a small PR with pytest-pep8 (ignoring all rules for now). Subsequent PR can fix the compliance and remove the rules from the ignored list.

**Comment by henn** [comment]
@knikolla, your plan sounds great.

**Comment by shwsun** [comment]
@zenhack One thing that I noticed while working with ``api.py`` and ``errors.py`` is that some existing code is not following pep8 correctly. 

For example, ``from haas.errors import *`` should be avoided. Right approach should be ``from haas.errors import BlockedError``, and intelligent tools like yapf will definitely remind programmers about this.

**Comment by zenhack** [comment]
Quoting (Jethro) Shuwen Sun (2016-07-10 13:44:26)

>    @zenhack One thing that I noticed while working with api.py and
>    errors.py is that some existing code is not following pep8 correctly.
>
>    For example, from haas.errors import * should be avoided. Right
>    approach should be from haas.errors import BlockedError, and
>    intelligent tools like yapf will definitely remind programmers about
>    this.

Indeed; that's why we haven't already implemented this -- it's not just
a matter of adding the checks, we also have to *fix everyting*. We
really should just tackle this. I have a hunch if we just keep saying
that it'll never happen (yay bystander syndrome?). If folks agree, I can
do it once the keystone stuff is in.

@henn, thoughts on this being my next task?

For the record, vim's python-mode complains about `import *` as well.

**Comment by henn** [comment]
@hil Let's discuss this at the meeting tomorrow. We have a number of housekeeping items tagged for 0.2 and 0.3.

**Comment by henn** [comment]
Let's continue discussion of this in #539 

Lots of good ideas!
