### ISSUE TITLE
Checking of project parameter in auth calls

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#623]
Currently, one could pass `None` or a string to the auth methods `have_project_access` and `require_project_access`.

Passing `None` is especially easy, since `network.creator` can be `None` or a `Project`.

I propose that we should check for `None` in these methods, and if we see it, make the output depend on just `self._have_admin()`. We should also update the documentation to reflect this.

Additionally, if it's straightforward, it would be nice to verify that `project` is an object of type `Project`, throwing an exception if it isn't. That would hopefully catch errors where folks passed in a string.

**Comment by zenhack** [comment]
So, actually, looking at that conditional, it's not obvious to me that we've even removed the loop. We've still got `project in network.access` in there. Do we know for certain that that actually shells out to the db instead of iterating?
