### ISSUE TITLE
list_project_networks is not documented in `rest_api.md`, and doesn't check authZ.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#630]
Whenever this call was added, it didn't get documented in the rest API docs. We need to be more careful in general about updating that document when modifying the API.

*also* it doesn't do any authZ checks at all. The other `list_project_*` calls all expect access to that project. I assume this is not what was intended.

Bumped into this when experimenting with the keystone plugin I've written.

//cc @gsilvis, @henn, @knikolla

**Comment by shwsun** [comment]
I believe ``list_project_networks`` is introduced in some recent PR. I do think about whether or not we should have something like this in every PR.
```
[] The commits are consistent with our contribution guidelines
[] You've added tests (if possible) to cover your change(s)
[] All tests are passing (tests/unit, pep8)
[] You've updated the documentation (if adding/changing api calls)
```

**Comment by zenhack** [comment]
Particularly updating the docs is something that seems to get forgotten frequently. I'm not trying to be accusitory of anyone, but I have observed that this is something that gets forgotten about frequently. We seem to be pretty decent on the first three points.

The immediate thing is that we should update the docs and add those authZ checks -- we have a bug, let's fix it.

I'm less attached to dealing with the meta-issue right now, but I suspect part of the problem is that adding api calls isn't something that happens frequently. Half the time when we do it the set of interns has completely turned over since the last time, and not everyone is even aware that that file exists.

I'm not big on just finding someone to blame when stuff like this happens; when multiple people are frequently making a mistake, the right solution is usually going to be some kind of process change, not just nagging people about it every time they mess up.

**Comment by shwsun** [comment]
Yes, the bug should be top priority. Could you add the bug label as well as the v0.2 milestone?

**Comment by zenhack** [comment]
Done.

**Comment by shwsun** [comment]
This is solved, we can close it.

**Comment by zenhack** [comment]
Yep, closing. Thanks for doing this.
