### ISSUE TITLE
Add auth to console code

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#647]
Currently, `show_console()`, `start_console()` and `stop_console()` don't do any auth checking.

We should do that!

**Comment by shwsun** [comment]
I vaguely remember that @zenhack said we want to rework on the console stuff? If so this one will get fixed naturally.

**Comment by zenhack** [comment]
Yeah, it'll have to be part of any design we implement there.

Is the console stuff even being (currently) actively used anywhere? If not I'd actually recommend just disabling it; It's horribly broken and probably a liability as is.

**Comment by henn** [comment]
@zenhack - I assigned this to you, since you're re-doing the console.

**Comment by zenhack** [comment]
@henn, great. Please read the proposal, as it contains a solution.

**Comment by xuhang57** [comment]
`console` implementation is done, right?  I can take this if it is just checking whether the user has the `admin` role or not @zenhack

**Comment by zenhack** [comment]
The HIL integration with obmd still needs to be done, so this will land as part of that (which requires a few other api changes; see the spec).

**Comment by xuhang57** [comment]
Got you. So this issue depends on some other features that still need to be implemented. Thinking we should have a label that indicates which issues are dependent on which.

**Comment by zenhack** [comment]
Since this is going to be part of obmd, and per the discussion in #953 we're planning on doing a release before now and being able to actually use obmd. Do we want to maybe move this issue to the 0.4 milestone?

**Comment by naved001** [comment]
yeah, moved it to 0.4 now.

**Comment by naved001** [comment]
see #1036
