### ISSUE TITLE
Restrict pep8 test to just sqlite DB flavor

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#652]
Right now, as part of #651, we introduced pep8 testing!

Because we have DB=postgres and DB=sqlite, though, it will now be run twice.

We could now add a conditional so that it only runs once per test. My suggestion is only to run it for `DB=sqlite`, since that tends to run faster anyhow.

**Comment by shwsun** [comment]
#654 addresses this, we can close it.

**Comment by knikolla** [comment]
Solved by #654
