### ISSUE TITLE
Improve CLI

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#662]
Currently, cli.py throws a `FailedAPICallException` when encountering errors, which is caught in _main()_ and causes an exit with status 1.

An error case is missed by this, where _cmd()_  can also throw an uncaught exception that doesn't necessarily lead to a `sys.exit(1)`:
```python
    def wrapped(*args, **kwargs):
        try:
            f(*args, **kwargs)
        except TypeError:
            # TODO TypeError is probably too broad here.
            sys.stderr.write('Invalid arguements.  Usage:\n')
            help(f.__name__)
   command_dict[f.__name__] = wrapped
```
I believe the right thing to do here is to also catch `TypeError` in _main()_.

@gsilvis @knikolla - appreciate your input.

**Comment by gsilvis** [comment]
No matter what, we should raise some error in the `except` clause there.  I chose to raise `FailedAPICallException`.  If we want the return code to be different in this case, we should make a new exception (`InvalidAPIArgumentsException`, perhaps?), raise that one, and catch that one in `main`.

**Comment by gsilvis** [comment]
On @knikolla's advice, made a new exception
