### ISSUE TITLE
HaaS tests failing

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#667]
I ran all tests on a fresh copy of the repo, and I got errors shown below:

    py.test tests/

========================================== ERRORS==============================
____________ ERROR collecting tests/integration/keystone.py ________________________
tests/integration/keystone.py:17: in <module>
    from keystoneauth1.identity import v3
E   ImportError: No module named keystoneauth1.identity
__________________________ ERROR collecting tests/unit/cli.py __________________________
import file mismatch:
imported module 'cli' has this __file__ attribute:
  /home/naved/hil/tests/integration/cli.py
which is not the same as the test file we want to collect:
  /home/naved/hil/tests/unit/cli.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_____________ ERROR at setup of TestNativeNetwork.test_isolated_networks ________________
def site_layout():
        """Load the file site-layout.json, and populate the database accordingly.
    
        This is meant to be used as a pytest fixture, but isn't declared
        here as such; individual modules should declare it as a fixture.
    
        Full documentation for the site-layout.json file format is located in
        ``docs/testing.md``.
        """
>       layout_json_data = open('site-layout.json')
E       IOError: [Errno 2] No such file or directory: 'site-layout.json'

haas/test_common.py:252: IOError

____ ERROR at setup of TestNetworkVlan.test_isolated_networks ________________________
def site_layout():
        """Load the file site-layout.json, and populate the database accordingly.
    
        This is meant to be used as a pytest fixture, but isn't declared
        here as such; individual modules should declare it as a fixture.
    
        Full documentation for the site-layout.json file format is located in
        ``docs/testing.md``.
        """
>       layout_json_data = open('site-layout.json')
E       IOError: [Errno 2] No such file or directory: 'site-layout.json'

haas/test_common.py:252: IOError

======================== FAILURES ===================================
________________________________________________________ TestHeadNode.test_headnode_deletion_while_running ________________________________________________________
self = <headnodes.TestHeadNode instance at 0x7fa15062b0e0>

    def test_headnode_deletion_while_running(self):
        api.project_create('anvil-nextgen')
>       api.headnode_create('hn-0', 'anvil-nextgen', 'base-headnode-2')

tests/deployment/headnodes.py:71: 

========= 1 failed, 372 passed, 1 skipped, 1 xfailed, 4 error in 169.01 seconds ============

I ran the tests on a VM running CentOS and directly on my pc running ubuntu, and I got the same results.

**Comment by shwsun** [comment]
It is not a issue and we are expecting `py.test tests/` failling.

The reason is,  deployment / integration requires correct environment setup to test. Like what is described in [doc/testing](https://github.com/CCI-MOC/hil/blob/master/docs/testing.md), you should only run `py.test tests/unit` and `py.test stress.py`

**Comment by zenhack** [comment]
@shwsun is correct. I'm going to close this.
