### ISSUE TITLE
Travis CI building failure due to upstream bug

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#675]
The travis CI build is failing. It's even failing for a previous commit that successfully passed all the checks. So I think something is up with Travis-CI. 
@knikolla @henn 
Here's a portion of the job log:

> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     return loadobj(APP, uri, name=name, **kw)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     return context.create()
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     return self.object_type.invoke(self)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 144, in invoke
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     **context.local_conf)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     val = callable(*args, **kw)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/urlmap.py", line 31, in urlmap_factory
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     app = loader.get_app(app_name, global_conf=global_conf)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 350, in get_app
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     name=name, global_conf=global_conf).create()
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 362, in app_context
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     APP, name=name, global_conf=global_conf)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 450, in get_context
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     global_additions=global_additions)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 559, in _pipeline_app_context
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     APP, pipeline[-1], global_conf)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 454, in get_context
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     section)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     object_type, name=use, global_conf=global_conf)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 406, in get_context
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     global_conf=global_conf)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     global_conf=global_conf)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     return loader.get_context(object_type, name, global_conf)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 620, in get_context
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     object_type, name=name)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 640, in find_egg_entry_point
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     pkg_resources.require(self.spec)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     needed = self.resolve(parse_requirements(requirements))
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone     raise VersionConflict(dist, req).with_context(dependent_req)
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone ContextualVersionConflict: (amqp 1.4.9 (/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/lib/python2.7/site-packages), Requirement.parse('amqp<3.0,>=2.1.1'), set(['kombu']))
> 
> 2016-10-31 19:06:58.614 5399 ERROR keystone 
> 
> unable to load app 0 (mountpoint='') (callable not found or import error)
> 
> *** no app loaded. going in full dynamic mode ***
> 
> *** uWSGI is running in multiple interpreter mode ***
> 
> spawned uWSGI master process (pid: 5399)
> 
> spawned uWSGI worker 1 (pid: 5421, cores: 1)
> 
> spawned uWSGI http 1 (pid: 5422)
> 
>   Using cached python_glanceclient-2.5.0-py2.py3-none-any.whl
> 
> Requirement already satisfied (use --upgrade to upgrade): keystoneauth1>=2.10.0 in ./.venv/lib/python2.7/site-packages (from python-openstackclient)
> 
> Collecting python-novaclient!=2.33.0,>=2.29.0 (from python-openstackclient)
> 
>   Using cached python_novaclient-6.0.0-py2.py3-none-any.whl
> 
> Collecting python-cinderclient!=1.7.0,!=1.7.1,>=1.6.0 (from python-openstackclient)
> 
>   Using cached python_cinderclient-1.9.0-py2.py3-none-any.whl
> 
> Requirement already satisfied (use --upgrade to upgrade): python-keystoneclient!=2.1.0,>=2.0.0 in ./.venv/lib/python2.7/site-packages (from python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): stevedore>=1.17.1 in ./.venv/lib/python2.7/site-packages (from osc-lib>=1.0.2->python-openstackclient)
> 
> Collecting os-client-config!=1.19.0,!=1.19.1,!=1.20.0,!=1.20.1,!=1.21.0,>=1.13.1 (from osc-lib>=1.0.2->python-openstackclient)
> 
>   Using cached os_client_config-1.22.0-py2.py3-none-any.whl
> 
> Collecting simplejson>=2.2.0 (from osc-lib>=1.0.2->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): funcsigs>=0.4; python_version == "2.7" or python_version == "2.6" in ./.venv/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): iso8601>=0.1.11 in ./.venv/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): debtcollector>=1.2.0 in ./.venv/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): pyparsing>=2.0.1 in ./.venv/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): netifaces>=0.10.4 in ./.venv/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): pytz>=2013.6 in ./.venv/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): monotonic>=0.6 in ./.venv/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): netaddr!=0.7.16,>=0.7.13 in ./.venv/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): PrettyTable<0.8,>=0.7 in ./.venv/lib/python2.7/site-packages (from cliff>=2.2.0->python-openstackclient)
> 
> Collecting unicodecsv>=0.8.0; python_version < "3.0" (from cliff>=2.2.0->python-openstackclient)
> 
> Collecting cmd2>=0.6.7 (from cliff>=2.2.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.1.0 in ./.venv/lib/python2.7/site-packages (from cliff>=2.2.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): requests>=2.10.0 in ./.venv/lib/python2.7/site-packages (from python-glanceclient>=2.5.0->python-openstackclient)
> 
> Collecting warlock!=1.3.0,<2,>=1.0.1 (from python-glanceclient>=2.5.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): positional>=1.1.1 in ./.venv/lib/python2.7/site-packages (from keystoneauth1>=2.10.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): oslo.serialization>=1.10.0 in ./.venv/lib/python2.7/site-packages (from python-novaclient!=2.33.0,>=2.29.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): oslo.config>=3.14.0 in ./.venv/lib/python2.7/site-packages (from python-keystoneclient!=2.1.0,>=2.0.0->python-openstackclient)
> 
> Collecting requestsexceptions>=1.1.1 (from os-client-config!=1.19.0,!=1.19.1,!=1.20.0,!=1.20.1,!=1.21.0,>=1.13.1->osc-lib>=1.0.2->python-openstackclient)
> 
>   Using cached requestsexceptions-1.1.3-py2.py3-none-any.whl
> 
> Collecting appdirs>=1.3.0 (from os-client-config!=1.19.0,!=1.19.1,!=1.20.0,!=1.20.1,!=1.21.0,>=1.13.1->osc-lib>=1.0.2->python-openstackclient)
> 
>   Using cached appdirs-1.4.0-py2.py3-none-any.whl
> 
> Requirement already satisfied (use --upgrade to upgrade): wrapt>=1.7.0 in ./.venv/lib/python2.7/site-packages (from debtcollector>=1.2.0->oslo.utils>=3.16.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): jsonschema<3,>=0.7 in ./.venv/lib/python2.7/site-packages (from warlock!=1.3.0,<2,>=1.0.1->python-glanceclient>=2.5.0->python-openstackclient)
> 
> Collecting jsonpatch<2,>=0.10 (from warlock!=1.3.0,<2,>=1.0.1->python-glanceclient>=2.5.0->python-openstackclient)
> 
>   Using cached jsonpatch-1.14-py2.py3-none-any.whl
> 
> Requirement already satisfied (use --upgrade to upgrade): msgpack-python>=0.4.0 in ./.venv/lib/python2.7/site-packages (from oslo.serialization>=1.10.0->python-novaclient!=2.33.0,>=2.29.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): rfc3986>=0.2.2 in ./.venv/lib/python2.7/site-packages (from oslo.config>=3.14.0->python-keystoneclient!=2.1.0,>=2.0.0->python-openstackclient)
> 
> Requirement already satisfied (use --upgrade to upgrade): functools32; python_version == "2.7" in ./.venv/lib/python2.7/site-packages (from jsonschema<3,>=0.7->warlock!=1.3.0,<2,>=1.0.1->python-glanceclient>=2.5.0->python-openstackclient)
> 
> Collecting jsonpointer>=1.9 (from jsonpatch<2,>=0.10->warlock!=1.3.0,<2,>=1.0.1->python-glanceclient>=2.5.0->python-openstackclient)
> 
>   Using cached jsonpointer-1.10-py2-none-any.whl
> 
> Installing collected packages: unicodecsv, cmd2, cliff, requestsexceptions, appdirs, os-client-config, simplejson, osc-lib, openstacksdk, jsonpointer, jsonpatch, warlock, python-glanceclient, python-novaclient, python-cinderclient, python-openstackclient
> 
> Successfully installed appdirs-1.4.0 cliff-2.2.0 cmd2-0.6.9 jsonpatch-1.14 jsonpointer-1.10 openstacksdk-0.9.8 os-client-config-1.22.0 osc-lib-1.2.0 python-cinderclient-1.9.0 python-glanceclient-2.5.0 python-novaclient-6.0.0 python-openstackclient-3.3.0 requestsexceptions-1.1.3 simplejson-3.10.0 unicodecsv-0.14.1 warlock-1.2.0
> 
> +source ../keystonerc
> 
> ++export OS_USERNAME=admin
> 
> ++OS_USERNAME=admin
> 
> ++export OS_PASSWORD=s3cr3t
> 
> ++OS_PASSWORD=s3cr3t
> 
> ++export OS_PROJECT_NAME=admin
> 
> ++OS_PROJECT_NAME=admin
> 
> ++export OS_USER_DOMAIN_ID=default
> 
> ++OS_USER_DOMAIN_ID=default
> 
> ++export OS_PROJECT_DOMAIN_ID=default
> 
> ++OS_PROJECT_DOMAIN_ID=default
> 
> ++export OS_IDENTITY_API_VERSION=3
> 
> ++OS_IDENTITY_API_VERSION=3
> 
> ++export OS_AUTH_URL=http://localhost:5000/v3
> 
> ++OS_AUTH_URL=http://localhost:5000/v3
> 
> +ADMIN_PASSWORD=s3cr3t
> 
> +./tools/sample_data.sh
> 
> Config file not found, using default configs.
> 
> 2016-10-31 19:07:02.563 5435 WARNING keystone.assignment.core [req-368e24c4-a757-4159-bb84-45eb752a76d3 - - - - -] Deprecated: Use of the identity driver config to automatically configure the same assignment driver has been deprecated, in the "O" release, the assignment driver will need to be expicitly configured if different than the default (SQL).
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications [req-368e24c4-a757-4159-bb84-45eb752a76d3 - - - - -] Failed to construct notifier
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications Traceback (most recent call last):
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/keystone/notifications.py", line 309, in _get_notifier
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications     transport = oslo_messaging.get_notification_transport(CONF)
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/oslo_messaging/notify/notifier.py", line 172, in get_notification_transport
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications     allowed_remote_exmods, aliases)
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/oslo_messaging/transport.py", line 192, in get_transport
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications     invoke_kwds=kwargs)
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/stevedore/driver.py", line 46, in __init__
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications     verify_requirements=verify_requirements,
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/stevedore/named.py", line 69, in __init__
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications     verify_requirements)
> 
> 2016-10-31 19:07:02.726 5435 ERROR keystone.notifications   File "/home/travis/build/CCI-MOC/hil/ci/keystone/keystone/.venv/local/lib/python2.7/site-packages/stevedore/extension.py", line 171, in _load_plugins

**Comment by knikolla** [comment]
This is related to upstream bug https://bugs.launchpad.net/oslo.messaging/+bug/1638263

Patch that fixes the issue https://review.openstack.org/#/c/392135/

**Comment by shwsun** [comment]
This is a bug from upstream, we are waiting the upstream to fix the bug and then remove our temporary workaround.

**Comment by naved001** [comment]
I'll leave this issue open until the bug from upstream is fixed and we have a permanent workaround.

**Comment by shwsun** [comment]
Upstream bug is fixed, we removed the tmp fix in #681 .
