### ISSUE TITLE
Current doc need some cleanup

### ISSUE THREAD

**Issue by shwsun** [CCI-MOC/hil#677]
I have spotted some markdown syntax error in our docs. For example, in [INSTALL.rst](https://github.com/CCI-MOC/hil/blob/master/docs/INSTALL.rst) command should always has a `$` before it, and the markdown writing style is not uniformed.

**Comment by naved001** [comment]
I can fix it. Besides putting a $ before a command, what other syntax errors are there?

**Comment by naved001** [comment]
I have made some changes you can see [here](https://github.com/CCI-MOC/hil/compare/master...naved001:cleanup_677)
What other markup errors do you see?

**Comment by shwsun** [comment]
@naved001 apparently some places in our doc is not right. What I want for this issue is to take a good look at serval important file first and address the ill-formatted part first.

**Comment by naved001** [comment]
I am not sure what changes to make apart from the ones that I've already made. Could you be more specific about the issues in the docs.

**Comment by naved001** [comment]
Just revisited `INSTALL.rst` it mostly looks fine to me. 

>  command should always has a $ before it

I actually think that's a bad idea because most of the time I want to copy and paste whole code blocks, putting the dollar signs before every command would make it painful to copy and paste it.

@shwsun 

I am in the favor of closing this issue because I don't see any glaring issues with the documentation formatting.

**Comment by shwsun** [comment]
By just look at the INSTALL.rst, I can spot a few places that are confusing. For example, we dont have a clear separation of things we want the user to type in the terminal and things that should goes into a file . Everything is fine with us simply because we worked on this so long and can just ask around. 

I don't think it is a high priority job but I dont think we should close it.

**Comment by xuhang57** [comment]
here too: https://github.com/CCI-MOC/hil/blob/master/docs/INSTALL-devel.rst

And `TESTING` in `INSTALL.rst`.

**Comment by zenhack** [comment]
I'd like to actually come up with a list of actionable items for this issue; Already mentioned:

- [ ] we dont have a clear separation of things we want the user to type in the terminal and things that should goes into a file

As it stands this issue is too open ended.

**Comment by xuhang57** [comment]
Maybe we should group all the documentation issues and find a sprint or two to solve them all together. Setting up the guidelines for the documentation would come first of course.

**Comment by zenhack** [comment]
We already have a documentation label. I'm going ot open a separate issue for the item I mentioned above. From there I think yeah, this is basically a question of triage. We could do a doc sprint, or just commit to adding a few doc issues to each sprint (which would keep future doc issues from getting lost after the initial sprint).

**Comment by zenhack** [comment]
Once we decide on a triage strategy, we can close this I think.

**Comment by xuhang57** [comment]
sounds good. @naved001 your call.

**Comment by xuhang57** [comment]
closing this. We can keep track of the triage strategy in the `Github issues issue` ? Or having a general issue on Docs cleanup.
