### ISSUE TITLE
Eradicate `import *` and make a linter to keep it out

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#678]
I just removed some "unused imports" from model.py and started getting all kinds of errors in tests that were doing `from haas.model import *` and then forgetting to import e.g. `logging`. I'm cleaning this instance up and will soon send a pr with correctly placed imports, but we ought to finaly get rid of `import *` and have travis check for it.

**Comment by shwsun** [comment]
Yep we should, that is a pep8 violation.

**Comment by naved001** [comment]
#855 fixes this.
