### ISSUE TITLE
HIL needs to write flash config

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#688]
Currently, at least the dell driver does not save the flash config, such that if a power outage happens the changes persist.

We need to:
a) Check all the drivers for this class of bug, and
b) fix it.

One possible way to address it would be to stick a "write ..." command in the switch driver's disconnect(). By doing it there rather than after each port mod, we might cut down on flash overwrites and potentially save some wear while speeding things up.

**Comment by henn** [comment]
Looking at #673, since there could be a time/flash wearing vs. consistency tradeoff maybe we could make it a tunable as to whether the `write ...` happens in disconnect() or after every change?

**Comment by zenhack** [comment]
One other option: we could recommend having the switch's stored config have all ports managed by HIL be *disconnected from everything*, so in the case of a power outage we fail-safe. This sidesteps the tricky problem of coordinating database commits and flash writes, as well having to worry about wearing out the flash.

**Comment by henn** [comment]
I like that.
Going into our discussion (hopefully later this week), I think we need to keep in mind that we a) don't want anyone to have access to networks they shouldn't, and b) should have a sane way for HIL providers to restore or reinstall their switch.

We've discussed 4 (mostly non-exclusive) ideas so far:

1. Write to flash (mentioned above)

2. (@zenhack's comment above) Have a default config that has all ports shut off. We may still need something like #687, since I noticed that once the switch was reset, using HIL to disconnect then reconnect the port gave me access to all VLANs

3. Have HIL maintain a copy of the switch config every time that is refreshed after every change.

4. Recommend that HIL providers have an external mechanism for backing up switch config.

**Comment by henn** [comment]
We just had some more discussion with @naved001 @knikolla @kylehogan @meng-sun and @gfaline. It sounds like a plausible solution would be to add a reset_nic(), in addition to having reset_port().

reset_nic() would be able to handle situations like needing to replace a dead switch with one or two others that might have different port capacities. After the nic was disconnected from the previous switch and connected to the new one, one could run reset_nic(). It could also handle moving a node between racks.

reset_port() would be helpful in cases where a switch was replaced in-kind, and one could simply run reset_port() on all of the ports to get them back to functional. It would also handle cases like we had with losing power, since we wouldn't know which nodes needed to be reset -- we just want to do them all.

**Comment by naved001** [comment]
closing this because #749 and #753 were merged.
