### ISSUE TITLE
More Keystone Travis breakage; probably an upstream change.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#691]
Failing build log on master:

https://travis-ci.org/CCI-MOC/hil/jobs/182325416

Note that the pr was passing prior to merging; presumably this was a matter of stuff shifting upstream in the interm.

Possibly related:

* https://github.com/CCI-MOC/hil/issues/675
* https://github.com/CCI-MOC/hil/pull/676
* https://github.com/CCI-MOC/hil/pull/681

This looks like it may be basically the same issue.

At this point I'm dubious of the notion that we can trust upstream to not screw up their dependency specs on a regular basis. There's talk on some of their issues/gerrit patches of wanting to just remove upper bounds entirely, which IMHO is *insane* and almost guaranteed to cause semi-frequent breakage. Breakage is the *definition* of a major version bump, so you should *always* have an upper bound. I don't feel like being the random outsider who comes in and argues with the developers of a project about their practices without having otherwise been very involved. So we need to figure out how our CI is going to keep working in spite of questionable choices from upstream.

Options:

1. Pin *all* of keystone's transitive dependencies. If we do this, I'd want to set up a schedule where we test with the latest stuff that un-pinned pulls in, and update if it works.
2. Pin oslo.messaging, and have a two-strikes rule or something, where if a package screws this up twice we pin it going forward.

We've historically been really bad at triaging; as-is I'm not sure I trust us to actually do the updating part of (1).

Thoughts?

//cc @henn, @shwsun, @knikolla

**Comment by knikolla** [comment]
Bug should be fixed upstream, until kombu 4.0.2 is released. Their [approach](https://review.openstack.org/#/c/408643/2/global-requirements.txt) is to != specific versions. So everytime a new one comes, stuff will break unless oslo.messaging is fixed to support the new versions. 

The second approach is easier, and kombu has already failed the 2 strikes, so I say we go with that.

**Comment by knikolla** [comment]
#693 is passing so can confirm that our gate is unblocked.

**Comment by henn** [comment]
I believe this was addressed by #736. Please re-open if not.
