### ISSUE TITLE
ipmitool error in node_power_off on a Sun

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#694]
Running `haas node_power_off sun-X` on haas-beta against one of the sun blades results in an error:
```
Unexpected status code: 500
Response text:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

This was found in `/var/log/httpd/error_log`:

```
Set Chassis Power Control to Down/Off failed: Insufficient privilege level
[...date...] [:error] [pid 1234] INFO:haas.ext.obm.ipmi:Nonzero exit status form ipmitool, args = ['chassis', 'power', 'off']
```

Interestingly, if I manually reconstruct what should be the ipmitool command, it works:
```
$ ipmitool -H X.Y.Z.A -U '' -P XXX chassis power off
Chassis Power Control: Down/Off
```

**Comment by naved001** [comment]
What you are manually reconstructing is different from what we have in the driver. 
In the driver we use the `lanplus` interface, so the command looks like `ipmitool -I lanplus -H X.Y.Z.A -U '' -P XXX chassis power off` which returns 
> Set Chassis Power Control to Down/Off failed: Insufficient privilege level

 If we use the `lan` interface, it works.

**Comment by naved001** [comment]
The issue was that the Service Processor (OBM) firmware was pretty old. I updated it to the latest version (only the SP, not the BIOS) and now `node_power_off` works. I only updated `sun-14` to test it; will update the other sun servers. So this is not a bug in HIL. I think we can close this issue now.

**Comment by henn** [comment]
This was solved by upgrading the firmware. Thanks @naved001 !
