### ISSUE TITLE
Tests are polluting each other's sets of extensions

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#697]
Somehow the tests are being polluted by each other; on #696, the migration test I added is having extensions it doesn't specify loaded, which breaks the test. I've managed to fix this on a debugging branch by running the migration tests in their own travis instance:

https://travis-ci.org/zenhack/hil/builds/187775909

(We may want to split more things out that way, since it would allow things to finish faster. We probably don't need to run the apache setup with sqlite, and it would be nice to speed things up, but that's another issue).

I *suspect* that some of the tests are importing extensions at top level, which are safe for the modules they're in, but that these are getting processed when the tests are collected, before separate processes are forked off to actually run the tests. If this is the case, a solution may be to just move all of these imports in fixtures.

**Comment by shwsun** [comment]
This is an interesting topic, and probably we can contribute our experience afterwards. For our own sake, I don't mind adopting the solution to move all of these imports into fixtures, as long as it can fix our problems. 

@henn @SahilTikale @knikolla   Any thoughts?

**Comment by zenhack** [comment]
My hunch was right; submitted a pr that fixes this. Once that's merged, rebasing #696 on top of it should solve the problems there.
