### ISSUE TITLE
Document port initial states

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#709]
It's not clear to me what state a port is expected to be in when it is registered with HIL.

For example, I just registered a Dell powerconnect port with HIL, ensured that it had no VLANs configured and was in access mode and connected it through HIL to a network. The result was that *every* VLAN ended up trunked to it.

#683 will help with this, though we'll still need to do the analysis for each driver to figure out what the initial state should be before networks are added to a port.

**Comment by naved001** [comment]
> ensured that it had no VLANs configured and was in access mode and connected it through HIL to a network. 

Afaik, in the powerconnects, when a new port is put into trunk mode it has access to every VLAN by default.

We should put that in `network-drivers.md` or do what I suggested here  #761

**Comment by zenhack** [comment]
Yeah, we should document this. I left a comment in #761 about that solution, but either way it seems like we could just add a change to the docs now, and worry about automating things later.

**Comment by xuhang57** [comment]
PR merged. Closing this.
