### ISSUE TITLE
Logging in the brocade driver

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#718]
The Brocade driver needs to handle exceptions thrown by the switch (like 204). @knikolla

**Comment by knikolla** [comment]
@naved001 Anything 2xx is not an error. What I meant during our discussion is logging the response of the switch when it returns 4xx status codes. There is not much we can do in terms of exception handling besides log the error text.

**Comment by knikolla** [comment]
Updated title to reflect issue.

**Comment by naved001** [comment]
Fixed by #702
