### ISSUE TITLE
Nexus switch register error msg

### ISSUE THREAD

**Issue by shwsun** [CCI-MOC/hil#723]
I have tested it on the hack-n-hil and seems like the driver for cisco switch is broken (or this model is not supported?)

@zenhack @henn I have manually setup the cisco switch but driver is not working, I dont have time right now to fix it. Any thoughts?

**Comment by zenhack** [comment]
@shwsun, it *should* support the nexus we have upstairs; we got that switch *specifically* for developing that driver. Can you be more specific than "not working?"

I'll be in tomorrow to hack on some stuff with @SahilTikale. We'll be done by 4:00 at the latest, so if you'll be around we can confer briefly if it's useful.

**Comment by shwsun** [comment]
Apologize for not being clear at the first place. what I have experienced is that I cant register the cisco switch. We can chat if you are around, I am in 591 now

**Comment by zenhack** [comment]
Can you share your haas.cfg?

**Comment by shwsun** [comment]
```
[shwsun@hack-n-hil: ~]$ cat haas.cfg
# This is an example haas.cfg file suitable for use for development without a
# full set of hardware (switches, nodes, libvirtd...). It can be used as-is,
# but using the vlan_pool allocator may also be desirable (see the  comments
# below).
[general]
log_level = debug

[auth]
require_authentication = True

[headnode]
trunk_nic = em4
base_imgs = img1, img2, img3, img4
libvirt_endpoint = qemu:///system

[client]
endpoint = http://127.0.0.1:5050

[database]
uri = sqlite:///haas.db
#uri = postgresql://<username>:<password>@<address>/<dbname>

[devel]
dry_run=False

[extensions]
haas.ext.switches.nexus =
#haas.ext.switches.dell =
haas.ext.obm.ipmi =
haas.ext.auth.null =

#haas.ext.network_allocators.null =

# Depending on what you're trying to do, you may want to use the vlan_pool
# network allocator instead of the null allocator. To do this, comment out the
# null allocator extension above, and uncomment the following:
#
haas.ext.network_allocators.vlan_pool =
#
[haas.ext.network_allocators.vlan_pool]
vlans = 2000-2010
```

**Comment by zenhack** [comment]
@shwsun, yeah that looks fine to me. Is there a stack trace or is the error just that one line? Failing that, my next thing to try would be to put a breakpoint at the top of that function and see what is actually calling it.

**Comment by naved001** [comment]
@shwsun try my haas.cfg file (make modifications as you need, I have some redundant stuff in it). Also make sure that you provide a **dummy vlan** when registering the switch. Without that it throws the `set_auth_backend` error

```
# This is an example haas.cfg file suitable for use for development without a
# full set of hardware (switches, nodes, libvirtd...). It can be used as-is,
# but using the vlan_pool allocator may also be desirable (see the  comments
# below).
[general]
log_level = debug

[auth]
require_authentication = True

[headnode]
trunk_nic = eth0
base_imgs = img1, img2, img3, img4
libvirt_endpoint = qemu:///system

[client]
endpoint = http://127.0.0.1:5000

[database]
uri = sqlite:///haas.db
#uri = postgresql://<username>:<password>@<address>/<dbname>

# [devel]
# dry_run=True

[extensions]
haas.ext.auth.null =
haas.ext.switches.dell =
haas.ext.switches.brocade =
haas.ext.switches.nexus =
haas.ext.obm.mock =
haas.ext.obm.ipmi =
haas.ext.auth.null =
# haas.ext.network_allocators.null =
haas.ext.network_allocators.vlan_pool =
[haas.ext.network_allocators.vlan_pool]
vlans = 1511-1520
haas.ext.auth.null =
```

Hope this resolves your issue!

**Comment by shwsun** [comment]
Thanks to point out the `dummy_vlan` Naved.

@zenhack @henn The problem we experienced is that registering nexus switch require a extra field - `dummy_vlan`. Register switches w/out the field should throw out a right error message instead of current `Fatal Error: set_auth_backed() called twice. Make sure you don't have conflicting extensions loaded.`

**Comment by zenhack** [comment]
Glad we tracked this down. Want to open a new issue re: errors & docs?

**Comment by shwsun** [comment]
Yeah, then we can close this one and use it as an reference.
