### ISSUE TITLE
Adding a get_node_status to the OBM driver

### ISSUE THREAD

**Issue by SahilTikale** [CCI-MOC/hil#724]
To make it easy for integrating HIL with provisioning systems like Ironic, MaaS etc we need to add 
a call `get_node_status` to the OBM driver that queries the current state of the node (powered on/powered off/Booted )and reports it as it is.

**Comment by naved001** [comment]
I am curious as to why does a provisioning system need to know the status of a node? AFAIK, we need to restart the node anyway so what's the purpose of checking if it's on or off beforehand.

**Comment by SahilTikale** [comment]
It is required to make HIL compatible to provisioning systems like IRONIC and MAAS. Ironic periodically checks the status of the nodes it controls. Any driver for Ironic has to provide this functionality. If HIL needs to support IRONIC or other such systems, we will need to functionality.

**Comment by naved001** [comment]
I can take this issue. Do you have a general idea what `get_node_status` should return? Besides, `on`, `off`.

**Comment by naved001** [comment]
This is now implemented in OBMd, we need to add the API to HIL. 

cc @zenhack

**Comment by zenhack** [comment]
Yep, and doing it will be absolutely trivial; just an auth check & redirect.
