### ISSUE TITLE
Nexus driver: wrong error msg and documentation fix

### ISSUE THREAD

**Issue by shwsun** [CCI-MOC/hil#726]
This bug is found out during a process of using Nexus driver. As mentioned in `network_driver.md`, registering cisco nexus switches required a extra field `dummy_field`. However, doing so w/out the extra field will not throw an error msg about `dummy_field` but something like `Fatal Error: set_auth_backed() called twice. Make sure you don't have conflicting extensions loaded.`

Another related problem is that we should specify how to use the `dummy_vlan`, i.e. in `network_driver.md` we should show that after configure the dummy vlan, user need to do 
`$ haas switch_register cisco-x nexus IP_ADDR USER_NAME PASSWD dummy_vlan`

The previous issue identified the problem is #723

**Comment by naved001** [comment]
The wrong message is a bug in the cli, not the driver. I'll push a fix now.

**Comment by naved001** [comment]
To add to this, the nexus driver allows the dummy_vlan to be set to 0. 
https://github.com/CCI-MOC/hil/blob/master/haas/ext/switches/nexus.py#L52
It should be a strict inequality on the left side.
