### ISSUE TITLE
Brocade Driver: disconnecting a network that's attached natively does not work

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#728]
Ran into this while testing #683. 

~~If a network is attached natively, then calling `node_detach_network` on that network does not actually~~ ~~remove it on the switch. ~~

When we remove a native network, the switchport defaults to VLAN 1 as it's native VLAN.

**Comment by naved001** [comment]
Closing this issue because it works correctly.

**Comment by naved001** [comment]
Re-opening this issue.

Discussed this in person with @radonm and @knikolla

**Comment by naved001** [comment]
@henn @zenhack I am putting this for 0.2 milestone because this seems pretty serious.

**Comment by naved001** [comment]
The fix introduced in #882 should take care of this too.

**Comment by xuhang57** [comment]
Sure, on it.

**Comment by naved001** [comment]
I had done some work for this, will make a PR. The deployment tests are failing for some odd reason; I'll post my findings soon.
