### ISSUE TITLE
Travis CI build failure

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#729]
Here are the details of my PR which was previously passing all the tests. https://travis-ci.org/CCI-MOC/hil/jobs/205965436

@henn @zenhack @knikolla

**Comment by naved001** [comment]
@SahilTikale the issue I was talking about.

**Comment by zenhack** [comment]
Look at the code, I'm actually a bit confused as to why it *was* working, or *is* working on master. It's complaining that additional_db is being called outside of a request context (and thus without access to db.session), which I would expect to cause problems. And indeed our list of fixtures has additonal_db before with_request_context.

@shwsun, your name is on the commit that put additional_db in that list; would appreciate an extra set of eyeballs.

**Comment by naved001** [comment]
@zenhack You are right. Changing the order in the list of fixtures fixes the errors for `tests/unit/model.py`, and `tests/unit/api/auth.py` 

```
pytestmark = pytest.mark.usefixtures('configure','with_request_context','fresh_database', 'additional_db', 'server_init')
```
Still looking at `tests/unit/ext/auth/database.py` where 1 test is failing.

**Comment by shwsun** [comment]
So I guess I don't need to dive into this now. Re: fixtures, IIRC, the order of them does matter, `additional_db` will add some more content to the database based on `fresh_db`. Probably it means I need to add some more doc/comment to our test infra

**Comment by naved001** [comment]
* @shwsun I [reordered the fixtures](https://github.com/CCI-MOC/hil/compare/master...naved001:test-fixes?expand=1), so tests are now passing for `sqlite` but tests that rely on `postgres` are failing. Here are the logs: https://travis-ci.org/naved001/hil/builds/207052073 If you could provide some insight that would be helpful. 

* The tests pass if you run in an old environment, so most likely some package has been updated which affects the db operations and/or how the fixtures are loaded (just spitballing here). SQLAlchemy was recently updated, but even then using an old version of SQLAlchemy didn't fix these issues.

**Comment by naved001** [comment]
Got it, the tests pass if we use `Flask-SQLAlchemy-2.1`. It was recently updated to 2.2. So restricting that would fix it. But I think we should still reorder the fixtures the right way instead of using an old version. For now I'll raise a PR to restrict the version of Flask-SQLAlchemy so that other PRs aren't blocked.

**Comment by zenhack** [comment]
Closing, since #730 is merged.
