### ISSUE TITLE
Isolate our CI from keystone

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#737]
So far, we've expended effort working around keystone problems in our CI (#691 #734 #675 #736) . In the latest version (#736), this was because of internal conflicts within the dependencies of keystone. Even though we've frozen the keystone repo itself at a particular commit, its dependencies in requirements.txt are mostly set as `>=$some_version`, meaning they can evolve/break.

One possible solution would be to freeze keystone (either as a python package or maybe in a container) so that we don't have to deal with its brokenness anymore.

Thoughts?

@zenhack @naved001 @knikolla @okrieg @pjd-nu @shwsun

**Comment by zenhack** [comment]
One nice change would be to separate out tasks on our build matrix a bit; we only need to run the keystone tests once per push. This way at least we'd get the feedback that it's just the keystone tests that broke.

If we isolate it this way, we could also use `pip freeze` to pin *every* package that gets installed.

**Comment by knikolla** [comment]
#739 resolves the lack of "<" in the requirements.txt file. That's because OpenStack has a common upper constraints file which all projects use when installing dependencies.

**Comment by shwsun** [comment]
Solved by #739
