### ISSUE TITLE
Better error handling in haas script

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#738]
In PR #683 we [hit an issue](https://github.com/CCI-MOC/hil/pull/683#issuecomment-285148932) that was made more difficult to debug because the generated `scripts/haas` entrypoint script has this block:

```python
try:
    execfile(__file__)
except NameError:
    print(e)
    exec(compile(open(__file__).read(), __file__, 'exec'))
```

In order to find the error (which was the somewhat cryptic `set_auth_backed() called twice. Make sure you don't have conflicting extensions loaded.`), we had to remove the `except NameError` clause so that we could see the real stacktrace.

We shouldn't be masking general errors like this.

**Comment by zenhack** [comment]
I just did:

```
grep NameError $(find * -name '*.py')
```

in my source repo, and it found nothing. Where is that code? I think it might be part of the entry_points mechanism, not our own source. I sure as heck didn't sign off on a PR with this in it...

**Comment by xuhang57** [comment]
Closing this since no one else could confirm this is an existing issue.

**Comment by naved001** [comment]
This hasn't been solved yet because we didn't spend enough time on it. The haas script still has the try except block

**Comment by xuhang57** [comment]
@naved001  would you mind putting a link to that file here? I could find any haas script under `/scripts/`
Thanks!

**Comment by naved001** [comment]
>  I think it might be part of the entry_points mechanism, not our own source.

Like @zenhack said, it's not in our source. After installing HIL, run `whereis hil` and open that up. I did this on a newer version of HIL and noticed that there's no try except block in that file:

```
# EASY-INSTALL-DEV-SCRIPT: 'hil==0.3.dev192+g9d75b35','hil'
__requires__ = 'hil==0.3.dev192+g9d75b35'
__import__('pkg_resources').require('hil==0.3.dev192+g9d75b35')
__file__ = '/home/naved/network-daemon/hil/scripts/hil'
exec(compile(open(__file__).read(), __file__, 'exec'))
```

I don't know what has changed

**Comment by xuhang57** [comment]
Hmm, then why would we care if that is not in our source code? I kinda lost there.

**Comment by naved001** [comment]
It showed up after we installed HIL. We don't understand exactly how that was happening. Maybe you are right and this has nothing to do with our own code, and just the way the package is installed.

**Comment by naved001** [comment]
but I won't just close this yet, until we reach a consensus. And right now, it looks like there's no try-except block. @zenhack you know anything else about it?

**Comment by jeremyfreudberg** [comment]
This commit looks somewhat relevant: https://github.com/pypa/setuptools/commit/1ed46282652e83edc8b88f64a279aacee182553d

**Comment by jeremyfreudberg** [comment]
I think resolving this TODO https://github.com/CCI-MOC/hil/blob/master/setup.py#L38 might also help

**Comment by zenhack** [comment]
Yeah, this is quite clearly not our bug. I am in favor of just closing this.

**Comment by jeremyfreudberg** [comment]
Yes, we can close this issue. Hopefully no one is relying on an ancient version of setuptools anymore.

**Comment by zenhack** [comment]
Closing.

**Comment by naved001** [comment]
I am proud of you @jeremyfreudberg
