### ISSUE TITLE
redundant code in switch driver

### ISSUE THREAD

**Issue by SahilTikale** [CCI-MOC/hil#751]
I found this code being repeated here.

https://github.com/CCI-MOC/hil/blob/master/haas/ext/switches/nexus.py#L102L113

Is it a mistake ? we should remove the redundant code.

**Comment by SahilTikale** [comment]
@zenhack just wanted know if this was a redundant code, or was the repetition deliberate.

**Comment by naved001** [comment]
you can close this because #752 got merged.

**Comment by zenhack** [comment]
Yep, closing.
