### ISSUE TITLE
List public networks as a regular user

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#765]
As mentioned in #453, we should have a function that lists public networks that any user can connect to in both the API and CLI.

**Comment by xuhang57** [comment]
@naved001 fell free to assign me to this one.

**Comment by naved001** [comment]
@xuhang57 are you still interested on working on this? otherwise @mosayyebzadeh wants to take this up!

**Comment by xuhang57** [comment]
@naved001 sorry for the delay. Feel free to let @mosayyebzadeh work on this. I will try to do some work if I could.

**Comment by xuhang57** [comment]
@naved001 I can start working on this today. @mosayyebzadeh Let me know if Amin hasn't started yet. ;)
