### ISSUE TITLE
create() in haas/client/user.py accepts a string rather than bool for admin privilege

### ISSUE THREAD

**Issue by Izhmash** [CCI-MOC/hil#795]
This should be cleaned up to keep the client library as clean and streamlined as possible.

Suggestion: `create()` should take a boolean rather than a string for `is_admin`.  The CLI rather than the client library should then handle the strings ('admin', 'regular').  The approach would be similar to `set_admin()`.

**Comment by xuhang57** [comment]
PR merged so close this now
