### ISSUE TITLE
Why is the default channel `vlan/native`

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#808]
If a user does [not provide](https://github.com/CCI-MOC/hil/blob/master/haas/api.py#L394) channel when running `haas node_connect_network` it [defaults to](https://github.com/CCI-MOC/hil/blob/master/haas/ext/network_allocators/vlan_pool.py#L64) `vlan/native`. It would be better if it defaults to tagged network i.e. `vlan/<number>`. In that case the user does not have to remember (or do a look up using show_network, adding another step) the VLAN ID for their network. And if they want to connect it natively they can pass `vlan/native` as argument.

**Comment by zenhack** [comment]
Are you guys finding the common case to be hooking it up tagged? I think we did it this way because we thought you'd "normally" want it to be set as the native vlan, only using explicit tags if you had more than one network per nic.

**Comment by henn** [comment]
I agree.
If a user always wants tagged, they can always specify `vlan/<number>`

Closing. Please re-open if you want to discuss further.

**Comment by henn** [comment]
If default-tagged networks were something folks desired, we could potentially do something as part of the CLI rewrite (#431).
