### ISSUE TITLE
Error checking in client/base.py failing to send message

### ISSUE THREAD

**Issue by Izhmash** [CCI-MOC/hil#813]
`Unexpected error: msg` was popping up when running commands like `haas list_nodes all`.  I discovered that it originated from client/base.py on line 46: `raise FailedAPICallException(e['msg'])`. 

However, when I printed `e` inside base.py by itself, I got a helpful error rather than just 'msg':
`{u'error': {u'message': u'The request you have made requires authentication.', u'code': 401, u'title': u'Unauthorized'}}`
Maybe this is just a very unique case, but otherwise it should probably be investigated.

**Comment by zenhack** [comment]
Maybe it should be e['message'] instead of msg?

**Comment by naved001** [comment]
#828 fixes this.
