### ISSUE TITLE
Keystone: missing OpenStack creds exception not printing

### ISSUE THREAD

**Issue by Izhmash** [CCI-MOC/hil#819]
Although there's `raise KeyError("Required openstack environment variable not set.")` on [line 143 of hil/cli.py](https://github.com/CCI-MOC/hil/blob/master/hil/cli.py#L143),  it only printed 'msg'  when I was missing one of the credentials.  Maybe related to #813 ?

**Comment by Izhmash** [comment]
I'll work on this now.

**Comment by naved001** [comment]
fixed by #828
