### ISSUE TITLE
Enable webhook for readthedocs so that our docs stay in sync.

### ISSUE THREAD

**Issue by SahilTikale** [CCI-MOC/hil#822]
Need to update the read the docs. Replace all instances of `haas` with `hil`

**Comment by naved001** [comment]
Ah, it should be run automatically and build the docs from latest master.  But anyway, I'll see why that is not happening.

**Comment by naved001** [comment]
@SahilTikale It's fixed now. Somebody with enough access should setup a webhook with readthedocs for it to build automatically everytime a PR is made.

**Comment by shwsun** [comment]
@SahilTikale Can you take a second look at the readthedoc page? I think the name changing thing is already handled. If you can confirm it then we can close this issue

**Comment by naved001** [comment]
@shwsun I triggered the rebuild to reflect the new change. But I would like to keep this issue open until someone with enough privileges enables the webhook for readthedocs so that it happens automatically in the future.

**Comment by naved001** [comment]
@SahilTikale or I don't have admin access to the HIL repo. @henn @knikolla can either of you enable the integration for readthedocs with our Repo?

**Comment by knikolla** [comment]
@naved001, I don't have access to the readthedocs admin page for hil, but I can add the webhook if you give me the payload url as per the guide.

**Comment by naved001** [comment]
@henn enabled it. I'll test it with a new PR before I close this.

**Comment by naved001** [comment]
Done, it works.
