### ISSUE TITLE
Improve Travis speeds: caching

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#833]
A lot of the test Travis time (about 4 mins in a [recent run](https://travis-ci.org/CCI-MOC/hil/jobs/255509334)) is spent doing pip install.

Maybe we could use Travis's [cache feature](https://docs.travis-ci.com/user/caching/) to cache the entire virtualenv?

We would need to be careful to invalidate it occasionally to be sure none of the dependencies broke us (as they have in the past).

**Comment by zenhack** [comment]
The other thing is, about half of that is keystone, which we could split off into its own section of the build matrix. I'm working on this on a branch, but still working out the kinks:

https://travis-ci.org/zenhack/hil/builds/255503286

It shaves off about 3 minutes total; the postgres run is the longest at 8 min, which previously was 11 min.

It might be good to have a more centralized list of possible optimizations; hard to keep track of 3 or 4 separate issues when thinking about this.

**Comment by henn** [comment]
RE: splitting off keystone, do we want to test `DB=postgres` **and** `DB=sqlite`?

RE: other optimizations, in addition to #834 , the other idea I had was to enable parallel tests for postgres by having tests use different DBs.

This could take the form of either using the PID as part of the DB name (assuming there were ncpu stable processes) or generating different ones with random UUIDs (maybe the former would be faster due to less creation/destruction).

Based on the smaller speed increase given by #832, this would only make sense to do after addressing this dependency caching issue.

**Comment by zenhack** [comment]
Quoting Jason Hennessey (2017-07-20 01:11:11)

>    RE: splitting off keystone, do we want to test DB=postgres and
>    DB=sqlite?

I would just do SQLite; the keystone auth backend doesn't touch the DB
at all, so it doesn't seem worth the expense.

>    RE: other optimizations, in addition to [1]#834 , the other idea I had
>    was to enable parallel tests for postgres by having tests use different
>    DBs.

Given that we basically didn't get a speedup for doing this with SQLite,
I'd want some reason to believe that Postgres would be different before
we expend the effort, esp. since it probably will be trickier.

**Comment by naved001** [comment]
> Given that we basically didn't get a speedup for doing this with SQLite,

Probably because we don't get multiple cores in the travis VM

**Comment by naved001** [comment]
I think we are caching pip packages. Installing HIL and its dependecies [takes 10-20 seconds](https://travis-ci.org/CCI-MOC/hil/jobs/380246801#L580) depending on the DB (for postgres we also install python-psycopg2 which doens't seem to get cached). And looking at the logs, it's pulling most of the stuff from the cache. Is it okay to close this issue now?

**Comment by zenhack** [comment]
Sounds good to me; closing.
