### ISSUE TITLE
Ability to enable/disable physical ports

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#841]
For nodes on the free list (especially on switches where we must assign a native VLAN), it might make sense to disable the port to ensure a node isn't able to communicate.

My thought is that we should have:
- API commands to enable/disable a port
- These commands should be runnable by an admin or the authorized node user
- These commands should be treated like NIC operations and placed into the NetworkingAction queue, causing any other commands against the NIC to fail.

Thoughts?

*\[EDIT\]*
In addition to being an explicit command, it might also make sense for this to happen by default when a node has no networks connected to it. This might make a good time to think about #842.

**Comment by naved001** [comment]
After our discussion in the HIL meeting yesterday (which I have summarized [here](https://github.com/CCI-MOC/hil/issues/847#issuecomment-319764311)) would we even need this API ?

**Comment by xuhang57** [comment]
@naved001 do we have a plan of supporting this API? If not, maybe we should close this.

**Comment by zenhack** [comment]
Adding all this to the API seems excessive to me. If @naved001 agrees, I'm fine with closing this.

**Comment by naved001** [comment]
>  happen by default when a node has no networks connected to it.

we could just do this (again, debatable if we want to or not), but definitely no need to expose the API for it.
