### ISSUE TITLE
Dell s3048-on switch driver/Dell NOS9

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#844]

**Comment by SahilTikale** [comment]
@naved001 is waiting on Dell support to report back on how to configure RESTapi server.

**Comment by naved001** [comment]
the dell s3100 doesn't have any APIs. So I got the s3048-on that has REST APIs.

**Comment by henn** [comment]
@naved001, @vsemp and I discussed using the REST XML API vs. using the REST API that runs CLI commands.

It sounded they're pretty similar when things are good, but that the straight XML API would likely give us better error messages back, so we should go with that when possible.

The only thing keeping us from that is due to the XML API not having support for listing the VLANs on a port. For that we can use the REST API encapsulation of CLI commands.

**Comment by naved001** [comment]
I am thinking of doing more stuff with the REST API encapsulation of CLI commands because the regular API is obnoxious and the [documentation](http://www.dell.com/support/home/us/en/19/product-support/product/force10-open-automation/manuals?lwp=rt) isn't helpful.

For example: When trying to do a GET on a VLAN; you can see that port `gige-1-3` has 3 untagged Vlans (10, 20 and 30) which is incorrect.

Moreover, since the directories here are messed up I can use PATCH to move an interface only to a new VLAN. (Also, this method of setting native vlan was discovered by @knikolla through trial and error because what's in the documentation doesn't work).

```
naved001:~/s3048$ curl -u blah:blah http://192.168.3.250:8008/api/running/dell/interfaces/interface/vlan-10 -X GET

<interface xmlns="http://www.dell.com/ns/dell:0.1/root" xmlns:y="http://tail-f.com/ns/rest"  xmlns:dell="http://www.dell.com/ns/dell:0.1/root">
  <name>vlan-10</name>
  <untagged>
    <name>gige-1-25</name>
  </untagged>
  <untagged>
    <name>gige-1-3</name>
  </untagged>
</interface>
naved001:~/s3048$ curl -u blah:blah http://192.168.3.250:8008/api/running/dell/interfaces/interface/vlan-20 -X GET

<interface xmlns="http://www.dell.com/ns/dell:0.1/root" xmlns:y="http://tail-f.com/ns/rest"  xmlns:dell="http://www.dell.com/ns/dell:0.1/root">
  <name>vlan-20</name>
  <untagged>
    <name>gige-1-25</name>
  </untagged>
  <untagged>
    <name>gige-1-3</name>
  </untagged>
</interface>
naved001:~/s3048$ curl -u blah:blah http://192.168.3.250:8008/api/running/dell/interfaces/interface/vlan-30 -X GET

<interface xmlns="http://www.dell.com/ns/dell:0.1/root" xmlns:y="http://tail-f.com/ns/rest"  xmlns:dell="http://www.dell.com/ns/dell:0.1/root">
  <name>vlan-30</name>
  <untagged>
    <name>gige-1-3</name>
  </untagged>
</interface>
```

The switch CLI, however, is accurate
```
    NUM    Status    Description                     Q Ports
*   1      Inactive                                  
    10     Inactive                                  
    20     Inactive                                  U Gi 1/25
    30     Inactive                                  U Gi 1/3
```

cc: @zenhack @knikolla

**Comment by naved001** [comment]
Looks like I can delete the untagged interfaces from the other Vlans by doing a DELETE on `long-url/untagged`. And then I can PATCH it to other interfaces.

But the delete itself might fail, if the interface/vlan was configured using the CLI. It's like if I set things using the CLI and then do a GET on that interface using the REST API, it gets out of sync. So I am not sure if I can count on the REST API to do things for this switch.

**Comment by zenhack** [comment]
Hard for me to weigh in with much insight having not played with the switch myself. It sounds like the CLI may be the more reliable option though.
