### ISSUE TITLE
Require a native VLAN before making trunked ones

### ISSUE THREAD

**Issue by Izhmash** [CCI-MOC/hil#846]
- Most switches always require a native VLAN
- Part of the solution to getting rid of the dummy VLAN
- Points of discussion:
    - Should this requirement be configurable?

**Comment by naved001** [comment]
Looks like we aren't gonna be forcing all switches to work the same way. #882 implements the title for the s3048-on switch, but not for other switches. 

We don't need to enforce this for other switches if a switch can just work fine without having a native vlan on a trunked port.

**Comment by naved001** [comment]
Do we want to enforce this policy on all switches or not? I am not sure if the network topology could get complicated if some switches are allowed to do certain things while others aren't (because they can't anyway).

**Comment by zenhack** [comment]
I think we're okay here; we can just enforce this on switches that need it. I'm going to close.
