### ISSUE TITLE
Last VLAN cannot be detached -> can't have port without VLAN

### ISSUE THREAD

**Issue by Izhmash** [CCI-MOC/hil#847]
- Strategy: 
    - Power off port when last VLAN (native) is detached
    - Power on port only if a native VLAN is attached
- Part of solution to removing the dummy VLAN

**Comment by naved001** [comment]
@henn, @Izhmash @SahilTikale and I discussed how we handle native VLANs in HIL.

In most of the switches we have, we just can't remove the native VLAN and it always defaults to VLAN 1 in most cases. 

Our current workaround for this is to set it to some dummy VLAN and then disable it. It seems like we are relying on a weird glitch in the switch that we can set native vlan of a port to a disabled vlan. @radonm thought this should not be possible and is most likely a bug.

We think we should make it a requirement to connect a native vlan first before they can add any trunking VLANs and the port would remain turned off until a native vlan is added. This is how it will work:

* For a node in free pool, the port connected to any of it's nic would be turned off; so no traffic can flow at all.
* A user attaches a node to his project - the port is still off.
* User runs `node_connect_network` (channel = vlan/native) that attaches the native vlan. and in the driver, in `enable native`/`set_native` we turn on the port, and then do the VLANy bits. That way a user doesn't explicitly turn on the port. After this, a user can connect as many trunked vlans as he wants like the old days.
* when a user removes a native network, we remove the network and also turn off the port. (And if they have trunked vlans, we complain or warn them)

@zenhack @okrieg @pjd-nu what do you guys think?

**Comment by naved001** [comment]
I think #846 and this would be bundled together

**Comment by zenhack** [comment]
@naved001, that sounds reasonable to me.

**Comment by naved001** [comment]
I am going to close this, since we'll be doing this on per switch basis 
* if a switch defaults to some vlan when the port is on, we will turn it off.  (dellnos9, brocade)
* if a switch has no vlans at all, then we don't have to turn it off. (powerconnects, nexus)
