### ISSUE TITLE
How do we manage dependencies for extension modules in HIL

### ISSUE THREAD

**Issue by SahilTikale** [CCI-MOC/hil#849]
Hi,
I am currently writing a driver for Juniper. I am using a specific python library called [PyEZ](https://github.com/Juniper/py-junos-eznc) for administering the switch. The library is a wrapper over [netconf](http://www.rfc-editor.org/rfc/rfc4741.txt). 

This library is a dependency requirement for the juniper driver only, therefore required only in HIL environments that manage Juniper switches. 

I was wondering how can we manage installing dependencies for such extensions without using setup.py so as not to bloat the initial HIL installations.

How are we doing this for the auth driver using keystone ? 

@zenhack any thoughts.

**Comment by zenhack** [comment]
Right now we're just leaving out the dependecy, and mentioning it in the docs. I've actually been thinking about this lately, and have some ideas for a better approach -- watch for a pr in the next few days. For now, just omit and document.

**Comment by zenhack** [comment]
So we just merged #851, which deals with this more systemtically. The thing to do would be to add another extra for that driver; I'm going to ask that you update that in your current pr. I'm closing this issue as well.
