### ISSUE TITLE
Mechanism to validate networking operations on a per-switch basis

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#854]
Right now we have a bunch of logic in a few API calls for validating networking actions before we queue them up. However, some switches are capable of operations that others are not, for example, the powerconnect and nexus drivers can support configurations where there are trunked vlans on a port but no native VLAN. #852 adds checks for this specific case to the API calls, but that's problematic because (1) it introduces VLA N specific code into the core, and (2) it forces all switches to operate at the lowest common denominator.

Instead, we should have a mechanism to query the driver for a given switch, to see if it is able to perform a given networking action *before* queueing it. This could then be called from the API server. This would probably just be a method on the `Switch` class. This method would not be allowed to actually communicate with the switch.

This is related to, but distinct from, the switch capabilities issue (#410).

**Comment by naved001** [comment]
I gave this a shot based on what we discussed in #876 

https://github.com/CCI-MOC/hil/compare/master...naved001:enforce-native-network?expand=1

If the idea sounds good, I''ll add unit tests and update the deployment tests (`tests/deployment/vlan_networks.py` fails for switches that need a native vlan to be set first).

**Comment by naved001** [comment]
Does the method we introduced in #882 solve this? Perhaps we could refactor that method into separate methods that check for legality for different cases. 

```python
def ensure_legal_operations():
    _native_network_required()
   _some_other_check_for_legality()
```

**Comment by zenhack** [comment]
It does; that's basically exactly what I was proposing in this issue. I'm going to close.
