### ISSUE TITLE
Handle switch errors gracefully

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#858]
In [hil/deferred.py](https://github.com/CCI-MOC/hil/blob/master/hil/deferred.py#L75), we currently don't catch any errors that might occur. In practice, this means that the Network Action Server (aka `hil serve_networks`) process dies.

This likely can happen for two reasons: a misconfiguration (ie - port name is incorrect/invalid), or a switch error.
 
We might be able to something more sensible in the case of transient switch or control path errors, like retrying an operation a couple times with increasing backoffs. Since the alternative is that the daemon dies, even taking 30 seconds to a minute or two would be fine.

This stemmed from [a conversation](https://github.com/CCI-MOC/hil/pull/856#issuecomment-323461136) in #856.

**Comment by naved001** [comment]
#929 will provide the mechanism for handling switch errors. Just that all our drivers will be updated to make use of it.

**Comment by xuhang57** [comment]
@naved001 your PR has merged. Should we close this? I know we have to update other switches. But maybe that should be in another issue?

**Comment by naved001** [comment]
@xuhang57 agreed. We are now catching errors in `deferred.py`, we just need to do what's described in #948
