### ISSUE TITLE
All extensions should be grouped under [extensions]

### ISSUE THREAD

**Issue by SahilTikale** [CCI-MOC/hil#868]
In `examples/hil.cfg.dev-no-hardware`  the `[hil.ext.network_allocators.vlan_pool]` is defined in the middle of extensions. The authentication extensions are defined after it.
Because of this when the `[hil.ext.network_allocators.vlan_pool]` is uncommented, running `hil-admin db create` fails, giving the following error:

```
$ hil-admin db create
ERROR: No authentication/authorization backend registered; make sure your hil.cfg loads an extension which provides the auth backend.
the authentication extensions are defined 
```
Make sure that all the extensions are defined together under  `[hil.ext.network_allocators.vlan_pool]` fixes the issue.

**Comment by naved001** [comment]
Ah, I see what you mean. The error code is due to the fact that we are calling the network pool allocator before registering any auth backend.
