### ISSUE TITLE
Cisco Switches - No Vlans in trunk mode = all vlans

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#878]
Apparently, if the switchport is in Trunking mode and we remove all vlans from it (revert port for example) then the switchport gets access to all vlans; which is the exact opposite of what we want.

The port membership is shown when you do a `do show vlan <id>` on any vlan.

@radonm discovered this on a Cisco Nexus 6000 switch (version 7.0) controlled by HIL in Kaizen environment.

**Comment by zenhack** [comment]
Huh. I seem to recall testing the nexus driver pretty extensively; is it possible that the loaner switch we have in PRB (3000 I think?) works differently?

**Comment by naved001** [comment]
Ah, the confusion was due to the fact how the switch reports the allowed vlans. 
For example, if all VLANs are allowed, then the allowed vlan list isn't displayed. 
```
r4-pA-c23-nexus3548(config-if)# do show running-config interface ethernet 1/17

!Command: show running-config interface Ethernet1/17
!Time: Mon Dec  4 20:00:19 2017

version 6.0(2)A1(1c)

interface Ethernet1/17
  switchport mode trunk
  switchport trunk native vlan 3750

``` 
Whereas, when you actually remove all vlans and then allow only specific VLANs. This is how the output of the command looks like
```
r4-pA-c23-nexus3548(config-if)# show running-config interface ethernet 1/17

!Command: show running-config interface Ethernet1/17
!Time: Mon Dec  4 20:24:18 2017

version 6.0(2)A1(1c)

interface Ethernet1/17
  switchport mode trunk
  switchport trunk allowed vlan 105,3700
```

However, the output of `show interface switchport` (which is what our drivers use)( shows all the vlans allowed correctly. so I am closing this issue.
