### ISSUE TITLE
links in the readme are broken

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#880]
Since we changed the domain name, the old ones no longer work. This is easy to solve, I am leaving this one for those who are new to github.

**Comment by naved001** [comment]
@razaaliraza

**Comment by ivanzaqqa** [comment]
can i do this? @naved001

**Comment by naved001** [comment]
@ivanzaqqa thanks for the willingness! But this one is already assigned to @razaaliraza

Have a look at other issues (with labels like easy, documentation) and you coud work on those.

**Comment by ivanzaqqa** [comment]
oke

**Comment by naved001** [comment]
@razaaliraza any updates on this?

**Comment by razaaliraza** [comment]
Generated pull request

https://github.com/CCI-MOC/hil/pull/892
