### ISSUE TITLE
Deployment tests for VLAN networks need to be rewritten

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#885]
With the fix introduced in #882, the vlan deployment tests (`tests/deployment/vlan_networks.py`) fail for Dell NOS9 based switches. We need to rewrite the deployment tests so that they work with both kind of switches.

(Whoever takes this should, ideally, run the tests on every switch we support).

**Comment by zenhack** [comment]
If we're no longer expecting every switch to work the same way, then it isn't necessarily valid to assume that all of the deployment tests *should* work for all of the switches. We should either generalize these or write some tests that work with the nos9 switches, but it may make sense to have some conditional logic to skip certain tests based on the hardware available.

**Comment by naved001** [comment]
> write some tests that work with the nos9 switches

Right, I did add some unit tests specifically for the nos9 switches. 

But I still want to be able to test the regular functionality that the vlan deployment tests were testing. I guess I could put some checks there (if `type == dellnos9` then do `certain things`) and tweak the tests a little.

**Comment by zenhack** [comment]
Maybe instead of `if type == dellnos9` we should be querying switch caps when we have those.

**Comment by naved001** [comment]
#895 closes this
