### ISSUE TITLE
Document our client library

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#903]
Right now there are no documentation for the HIL client library and we should add that soon.

@tpd001 suggested that we could have:

> 
> 1. A summary README.md at least specifying the main interfaces and how to use them, or an update to the readthedocs page which covers the client library.  Some examples would be helpful.   Any debug controls should be described.
> 
> 2.  A requirements.txt file

cc: @SahilTikale

**Comment by naved001** [comment]
@razaaliraza I am assigning this to you. This seems like a good way to start learning more about the code and I'll be available to help/review.

**Comment by xuhang57** [comment]
I could look into this. A discussion with @naved001 would be handy.

**Comment by xuhang57** [comment]
@zenhack @naved001 so an outline for the `README.md` here, do we need to cover anything else?:

### HIL Python Client API
#### How to get started?
```
import requests
import os
from hil.client.client import Client, RequestsHTTPClient

ep = os.environ.get('HIL_ENDPOINT')
basic_username = os.getenv('HIL_USERNAME')
basic_password = os.getenv('HIL_PASSWORD')

http_client = RequestsHTTPClient()
http_client.auth = (basic_username, basic_password)
C = Client(ep, http_client)
print C.project.create("test-project")

```

**Comment by naved001** [comment]
* I don't think you don't need to import requests, the client library does that for you.

What you have provided otherwise is a decent sample to show how to use the client object. You could also link the [leasing script](https://github.com/CCI-MOC/hil/blob/master/examples/leasing/node_release_script.py) as a more comprehensive example.

* And to be able to import the hil client modules, I just do a `pip install git+https://github.com/cci-moc/hil` which puts those modules in the path. Advanced users could pick the files themselves. Would be nice to mention this. I don't think there's need to document every other call.

**Comment by xuhang57** [comment]
PR merged. W now have the doc on our client library. We need to add more examples in the doc though.
