### ISSUE TITLE
`get_port_networks()` doesn't read inactive vlans (on the powerconnect switch).

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#921]
```
Trunking VLANs Enabled: 1511
                        1512 (Inactive)
``` 
VS
```
Trunking VLANs Enabled: 1511-1512
```
This was causing deployment tests to fail on the powerconnect switch.
From the comment [here](https://github.com/CCI-MOC/hil/blob/master/hil/ext/switches/_dell_base.py#L59-L61) it's not clear if this is the intended behavior or not.

**Comment by zenhack** [comment]
From the code it looks like the issue may actually be that it's split on to the next line.

**Comment by naved001** [comment]
Since we are telling hil admins to create all VLANs that HIL will be using, do we still need to worry about reading inactive VLANs? I guess not, if you agree you can close this.

**Comment by zenhack** [comment]
Per the above, I don't think `(Inactive) ` is what's causing the problem; I suspect it's the line break.

**Comment by naved001** [comment]
> I suspect it's the line break.

I think so too. So I think we should update the method to read the inactive VLANs too because those VLANs **are allowed** on that switchport and may get activated in the future.

**Comment by naved001** [comment]
#998 fixes this.
