### ISSUE TITLE
Unimplemented api calls in client library

### ISSUE THREAD

**Issue by Izhmash** [CCI-MOC/hil#924]
Neither Node's nor Switch's `register()` functions are implemented in the client library.   Since every call should be accessible in the client library, this should be fixed.

**Comment by zenhack** [comment]
Yeah, I think there are a number of calls that aren't there. They're not hard to add. It would be good to make a list.

**Comment by naved001** [comment]
1. `node_register()`
2. `switch_register()`
3. `node_set_bootdev()`
69. `metadata_set()`
420. `metadata_delete()`
69. `list_network_attachments()`

`start_console()` and `stop_console()` use the client library, but `show_console()` doesn't. That's weird.
The headnode stuff doesn't use any client library calls, but we don't need to add support for it either.

cc: @SahilTikale

**Comment by zenhack** [comment]
The console stuff probably isn't worth bothering with until the obmd stuff lands (or maybe we should do that at the same time).

I agree, we can omit the headnode stuff. Though it would be trivial to add if someone were going to just slog through and add all of these in one pass.

I edited your comment to turn it into a checklist; hope that's cool.

**Comment by xuhang57** [comment]
Will look into this. Trying to figure out how to use the CLI for these operations first.

**Comment by zenhack** [comment]
Cool, I'l assign you. I've also changed the title of the issue to reflect the current thinking.

**Comment by naved001** [comment]
Complete!
