### ISSUE TITLE
Mass Open Cloud administrative updates

### ISSUE THREAD

**Issue by Izhmash** [CCI-MOC/hil#933]
A lot of the HIL code still shows "Massachusetts Open Cloud" and the README doesn't yet direct to the new website.  The copyright mentions still show this too, and many of them have old dates.

**Comment by xuhang57** [comment]
Also, do we need to update the date in the copyright statement? For example:
https://github.com/CCI-MOC/hil/blob/master/hil/api.py#L1

it is very outdated. And I can take care of this if it is okay.

**Comment by xuhang57** [comment]
PR merged so close this now.

**Comment by naved001** [comment]
Thanks! Lucas is on a roll here!
