### ISSUE TITLE
`user` is a reserved keyword in postgres

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#956]
If we use database authentication, then we create a table called [`user`](https://github.com/CCI-MOC/hil/blob/master/hil/ext/auth/database.py#L22) which happens to be a reserved keyword in postgres.

```
hil=> select * from user;
 current_user 
--------------
 hil
(1 row)
```

to get the correct response, I have to do `select * from "user";`

I guess we should avoid using reserved keywords. Don't know how big of an issue this is, might not be an issue at all, but I think it's worth discussing if something like this could lead to db problems in future.

**Comment by zenhack** [comment]
SQLAlchemy is smart enough to manage this, which is how it hasn't been raised thus far. I noticed this a while back, but I don't think it's a problem. I certainly don't think it's worth a migration script.

**Comment by naved001** [comment]
cool, I am gonna close this then.
