### ISSUE TITLE
Flask 0.10 -> 0.11?

### ISSUE THREAD

**Issue by xuhang57** [CCI-MOC/hil#975]
Not sure whether we want to bother ourselves to upgrade the flask from `0.10` to `0.11` (current stable version is `0.12`). And it seems to be a not-so-easy upgrade, at least, flask adds a new cli and we may need to change our migrations process as well (by using the new flask cli). Thoughts?

![screen shot 2018-03-12 at 10 06 31](https://user-images.githubusercontent.com/7245860/37288358-73635140-25dd-11e8-87eb-e2c0e0767810.png)

**Comment by zenhack** [comment]
It doesn't sound like they're actually dropping Flask-Script yet; I think we could upgrade flask without having to switch to their CLI tool at the same time.

The api for the new thing also isn't dramatically different; I don't think porting we be a ton of work. The big question is how to we wrangle Flask-Migrations?

**Comment by xuhang57** [comment]
True, but are you saying that upgrading to `0.11` will break the Flask-Migrations? Or break our current setup about it?

I haven't figured everything out yet. According to https://flask-migrate.readthedocs.io/en/latest/
We should be able to do migrations with the flask CLI (we have to construct it for sure) and it seems like it is gonna take some effort.

**Comment by zenhack** [comment]
@xuhang57, we're already using Flask-Script, as Flask-Migrate has built-in support for it: https://flask-script.readthedocs.io/en/latest/

Upgrading Flask shouldn't break anything; we can keep right-on using Flask-Script for the migration script, and it probably makes sense to do so until Flask-Migrate supports the thing that's been added to Flask core.

The warning on the Flask-Script page is aimed at potential new users, telling them that Flask-Script is *redundant* with functionality now in Flask core, but it's not *broken* afaik.
