### ISSUE TITLE
Bad log_dir in hil.cfg crashes server

### ISSUE THREAD

**Issue by Izhmash** [CCI-MOC/hil#976]
If `log_dir` is set to something inappropriate, the server will crash an report `Unexpected error:`.
This error should report something more useful to the user.  After this is fixed, perhaps it could be added to the config precheck (#966)

**Comment by zenhack** [comment]
Poked at this a little bit, this should be a simple matter of catching `IOError` specifically in the cli and handling it. we'll want to wait until #969 is merged though, since it will likely cause conflicts.

**Comment by naved001** [comment]
Wouldn't what I suggest [here](https://github.com/CCI-MOC/hil/pull/966#discussion_r174318836) fix this?

**Comment by Izhmash** [comment]
It could still crash if the directory can't be accessed.  The config check in #966 will only check for malformed directories, not if they exist or not.

**Comment by naved001** [comment]
Fixed by #966
