### ISSUE TITLE
Go error failing Travis builds

### ISSUE THREAD

**Issue by Izhmash** [CCI-MOC/hil#985]
`/home/travis/gopath/src/github.com/lib/pq/notify.go:787: undefined: time.Until` is causing the builds to fail.  I believe it is because the Go version on Travis is a pre-1.8 version.

**Comment by Izhmash** [comment]
I'm trying to get Travis to upgrade Go with some edits to the yaml and a new Go install script.

**Comment by Izhmash** [comment]
I've tried a few different ways of installation: using gimme, using apt-get with the golang PPA, installing directly from the go 1.10 tarball.  Each time, the Go version afterwards is still `go1.7.4 linux/amd64`.  Does anyone have any input on this issue?

**Comment by naved001** [comment]
https://travis-ci.org/CCI-MOC/hil/jobs/359043937#L46 From this, it looks like the go version is actually 1.8.3

**Comment by naved001** [comment]
Relevant, https://github.com/jmhodges/howsmyssl/issues/167

**Comment by zenhack** [comment]
We do seem to be using 1.7:

https://travis-ci.org/zenhack/hil/jobs/359575944#L3376

I'll continue to try to figure out how to get >1.8 in the vm.
